### ISSUE TITLE
「Active Record クエリインターフェイス」内の誤訳

### ISSUE THREAD

**Issue by sidemt** [yasslab/railsguides.jp#1017]
「Active Record クエリインターフェイス」＞「13.2 関連付けの一括読み込みで条件を指定する」に以下の日本語訳があります。

>SQL断片化 (fragmentation) を避けるためには、references を指定して強制的にテーブルをjoinする必要があります。

英語の原文は以下の通りです。

>For SQL-fragments you need to use references to force joined tables:

ここで言われている「SQL-fragments」とは断片化(fragmentation)ではなく、生のSQLの文字列のことではないかと思います。
日本語版の同じページ12.1.1では「SQLフラグメント文字列」と訳されています。

修正するとしたら、以下のような訳になるかと思います。

「SQLフラグメント文字列を渡す場合には、強制的に結合テーブルとして扱うために `references` を使用する必要があります。」

下記、 references メソッドの説明とも一致して意味が通るように思います。
https://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-references

該当箇所：
[日本語 13.2 関連付けの一括読み込みで条件を指定する](https://railsguides.jp/active_record_querying.html#%E9%96%A2%E9%80%A3%E4%BB%98%E3%81%91%E3%81%AE%E4%B8%80%E6%8B%AC%E8%AA%AD%E3%81%BF%E8%BE%BC%E3%81%BF%E3%81%A7%E6%9D%A1%E4%BB%B6%E3%82%92%E6%8C%87%E5%AE%9A%E3%81%99%E3%82%8B)
[英語 14.2 Specifying Conditions on Eager Loaded Associations](https://guides.rubyonrails.org/active_record_querying.html#specifying-conditions-on-eager-loaded-associations)

**Comment by yasulab** [comment]
こちら #1018 で対応されたので Close しますね! 対応ありがとうございます (＞人＜ )✨
