### ISSUE TITLE
4_0_release_notes(3.2 Action Pack)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#103]
```
Routing concerns (commit) - In the routing DSL, factor out common subroutes (comments from /posts/1/comments and /videos/1/comments).
```
=>
```
ルーティングでの配慮 (コミット) - DSLをルーティングする際に、共通となるサブルーティング (subroutes) を除外する (/posts/1/commentsと/videos/1/commentsにおけるcommentsなど)。
```

ですが、

+ routingで利用可能な`concern`メソッドのことだと思います。[cf](http://railsguides.jp/routing.html#%E3%83%AB%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0%E3%81%AE%E3%80%8Cconcern%E3%80%8D%E6%A9%9F%E8%83%BD)。ですので`ルーティングの「concern」機能`のような見出しがいいのではないでしょうか？

+ `In the routing DSL`は`routes.rb内で`もしくは`ルーティング用のDSLで`のような訳がいいのではないでしょうか？

**Comment by hachi8833** [comment]
ご指摘ありがとうございます。concernってコントローラとか以外にもあったんですね(汗

**Comment by yui-knk** [comment]
ありがとうございましたー
