### ISSUE TITLE
rails db:create の記述が抜けている

### ISSUE THREAD

**Issue by wonder-boooy** [yasslab/railsguides.jp#1041]
# Summary

[Railsをはじめよう - 4.1 Webサーバーを起動する -](https://railsguides.jp/getting_started.html#web%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%82%92%E8%B5%B7%E5%8B%95%E3%81%99%E3%82%8B) の前に`rails db:create`が必要

# Detail

`rails db:create`せずに`rails server`を実行すると`ActiveRecord::NoDatabaseError`が発生するため、その手順を追記する必要がある。

`guides/source/ja/getting_started.md`の174行目周辺

**Comment by yasulab** [comment]
AWS Cloud9 で開発環境を統一しているRailsチュートリアルなどと比べて、（原著を含め）Railsガイドでは開発環境ごとの細かな違いを記載しない方針で進めているようですので、こちら一旦 Close しますね >< 💦 （自分の環境では SQLite が動いているため特に問題なかったです!）

フィードバックありがとうございました！(＞人＜ )💖
