### ISSUE TITLE
4-2 パスの不一致　確認

### ISSUE THREAD

**Issue by yoshiki707** [yasslab/railsguides.jp#1043]
### 発生箇所　4-2
> それでは`app/views/welcome/index.html.erb`を開き、中身を以下に置き換えましょう。

上記のパスですが

`app/views/articles/index.html.erb`

こちらではないでしょうか？？

V6.1を参照しています。

**Comment by yasulab** [comment]
こちら現在の最新版では修正されているかなと思いますので、一旦 Close しますね。フィードバックありがとうございました！(＞人＜ )💖
