### ISSUE TITLE
4_0_release_notes(3.3 一般)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#105]
> Thread safe by default (commit) - Rails can run in threaded app servers without additional configuration.
> Note: Check that the gems you are using are threadsafe.

=>

> デフォルトでのスレッドセーフ提供 (コミット) - Railsは追加設定なしでスレッド化されます。
> Note: 追加したgemも同様にスレッドセーフであるかどうかをチェックしておいてください。

相談です。こちら、`NOTE:`(あの青囲みに変換される)を意識している書き方だと思いますか？
もしそうなら、一度本家にPR投げてみます。

**Comment by yasulab** [comment]
> 一度本家にPR投げてみます。

おぉ、確かにプルリクチャンスっぽいですね! PRお願いしま〜す :+1:

**Comment by yasulab** [comment]
@yui-knk そういえばコチラって本家に merge されたんでしたっけ?

**Comment by yui-knk** [comment]
いまPRをなげました..

https://github.com/rails/rails/pull/19308

**Comment by yui-knk** [comment]
mergeされました :)

**Comment by yasulab** [comment]
あら、`NOTE:` が反応しない... :sweat_drops: 

![screen shot 2015-03-13 at 14 50 47](https://cloud.githubusercontent.com/assets/155807/6633730/835d0a52-c990-11e4-919f-1d13fd5b1cc2.png)

**Comment by yui-knk** [comment]
@yasulab  先頭に半角スペースが入っていたいたりしませんか？

**Comment by yasulab** [comment]
@yui-knk 半角スペースが入ってました (癖で... :sweat_drops: ) ありがとうございます! :blush:

**Comment by yui-knk** [comment]
:smile:
