### ISSUE TITLE
生成後のHTMLでRails APIへのリンクが edgeapi.rubyonrails.org になっている

### ISSUE THREAD

**Issue by hazi** [yasslab/railsguides.jp#1060]
Rails Guide の現在のページを確認すると、Rails APIへのリンクが http://edgeapi.rubyonrails.org になっている箇所が多数あります。
例: https://railsguides.jp/active_record_querying.html#enums

[Rails ガイドのガイドライン - 4 APIにリンクする](https://railsguides.jp/ruby_on_rails_guides_guidelines.html#apiにリンクする) を拝見する限り、URLはバージョンに合わせたものに自動でリンクするようになっており、ソースも確認しましたが  http://edgeapi.rubyonrails.org へリンクしているものはなさそうでした。

ビルド時に何かしらのパラメーターが抜けているために、リンクが https://api.rubyonrails.org/{VERSION}/classes/... であるべきところが http://edgeapi.rubyonrails.org/classes/... になってしまっているのかなと思ったのですが、いかがでしょうか。

**Comment by yasulab** [comment]
ご連絡ありがとうございます！後ほどビルド周りのコードを調べてみますね 👀💨✨

**Comment by yasulab** [comment]
こちら調べてみたところ、現在は次のような状態になっているのが原因かなと考えています :eyes: 💭 

1. Renderer が日本語でも正しく動くように日本語特有の処理を Renderer に入れている
2. upstream から pull する度に conflict が発生するので、現在はハードフォークしている ([renderer_ja.rb](https://github.com/yasslab/railsguides.jp/tree/master/guides/rails_guides/markdown))
3. [renderer.rb](https://github.com/yasslab/railsguides.jp/blob/master/guides/rails_guides/markdown/renderer.rb) にある `api_link` メソッドなどが、railsguides.jp ではまだ反映されていない

そこまでコード量が大きくないのでハードフォークを止められないか調査・検証したり、当該メソッドを移行したりなどいくつか対応方法がありそうですね 🤔💭 現在リソースをあまり割ける状態ではないのですぐには対応できないかなと思いますが、ひとまず後で見返しやすいようにラベルだけ貼っておきました! :eyes: ✅ 

ご指摘ありがとうございました...!! (＞人＜ )✨

**Comment by hazi** [comment]
手元で `rake guides:generate:dash ALL=1 GUIDES_LANGUAGE=ja RAILS_VERSION=v6.1.4` を実行する限り URLは ` https://api.rubyonrails.org/` になっているので、RAILS_VERSION が抜けているだけかと思ったんですが違いますか？

**Comment by yasulab** [comment]
なるほど...!? では自分の勘違いかもしれないですね! 😂😂😂

> rake guides:generate:html ALL=1 GUIDES_LANGUAGE=ja RAILS_VERSION=v6.1.4

コマンドの実行例ありがとうございます! あとで試してみますね 👀💨✨

**Comment by yasulab** [comment]
こちら #1062 のような仕組みで恐らくうまく動きそうなので、後日、タイミングを見計らってマージ＆デプロイしますね 🛠💨✨ (本日は別件の作業が色々と立て込んでいるので... 😂)

**Comment by yasulab** [comment]
@hazi こちらお待たせしました! 先ほど対応が完了し、現在は下記の通りヘッダーのバージョン表記に合わせた API へのリンクになっているかなと思います :eyes: ✅  また何かあればお気軽にご連絡 or プルリク送っていただけると嬉しいです! 😆✨

例: https://railsguides.jp/active_record_querying.html#enums
![image](https://user-images.githubusercontent.com/155807/125728318-d0eec553-aba3-4398-9da5-81990a3fed8f.png)

**Comment by hazi** [comment]
ご対応いただきありがとうございました！
今回で色々と仕組みを把握できたので、次回から極力PR送るようにします！

**Comment by yasulab** [comment]
ありがとうございます！😻🆒✨

今回の対応もそうでしたが、デプロイ部分のワークフローは非公開となっており、場合によってはそちらで対応した方が良い場面もありますので、もし PR で対応しづらい箇所などありましたらお気軽にご連絡いただければ...!! (＞人＜ )💖
