### ISSUE TITLE
v6.1で追加された水平シャーディングのドキュメントを追加する

### ISSUE THREAD

**Issue by wengtadashi** [yasslab/railsguides.jp#1066]
# Summary
v6.1で水平シャーディング機能が実装されたが今のドキュメントには記載されていない
今のドキュメント：https://railsguides.jp/active_record_multiple_databases.html
本家は記載済み：https://guides.rubyonrails.org/active_record_multiple_databases.html

@yasulab @hachi8833 
PR出してもいいですか？

**Comment by yasulab** [comment]
@wengtadashi ご提案ありがとうございます！もしよければ PR を是非...!!! (＞人＜ )✨
他にも何か気になる点などあればお気軽にメンションしていただけると嬉しいです! 🙏 💖
