### ISSUE TITLE
タイプミス（誤字）

### ISSUE THREAD

**Issue by ino-via** [yasslab/railsguides.jp#1070]
https://railsguides.jp/getting_started.html

## overview
- 小さいことですけど、誤字？を見つけました

## 本文
しかし、link_toヘルパーを用いるとさらに便利になります。link_toヘルパーの第1引数はリンクテキスト、第2引数はリンク先です。第2引数にモデルオブジェクトを渡すと、link_toが適切`は`パスヘルパーを呼び出してオブジェクトをパスに変換します。たとえば、link_toにarticleを渡すとarticle_pathというパスヘルパーが呼び出されます。これを用いると、 app/views/articles/index.html.erbは以下のように書き換えられます。

## 修正文
しかし、link_toヘルパーを用いるとさらに便利になります。link_toヘルパーの第1引数はリンクテキスト、第2引数はリンク先です。第2引数にモデルオブジェクトを渡すと、link_toが適切`な`パスヘルパーを呼び出してオブジェクトをパスに変換します。たとえば、link_toにarticleを渡すとarticle_pathというパスヘルパーが呼び出されます。これを用いると、 app/views/articles/index.html.erbは以下のように書き換えられます。

**Comment by yasulab** [comment]
ご報告ありがとうございます！よければ PR にしてお送りいただけると嬉しいです！(＞人＜ )✨

**Comment by yasulab** [comment]
Fixed by https://github.com/yasslab/railsguides.jp/pull/1071
