### ISSUE TITLE
ディレクティブ or 命令?

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#109]
[アセットパイプライン](http://railsguides.jp/asset_pipeline.html)の中でよく `ディレクティブ (directive)` という単語が出てくるのですが、コチラ、例えば `命令` や `文` といった感じに訳すのはいかがでしょうか? 

具体的なイメージとしてはこんな感じです:

- 現状: `require_treeディレクティブを使用すると、これらのファイルを即座にアプリケーションから利用できます。require_treeの詳細についてはマニフェストファイルとディレクティブを参照してください`
- 提案: `require_tree文を使用すると、これらのファイルを即座にアプリケーションから利用できます。require_treeの詳細についてはマニフェストファイルと命令文を参照してください`

理由としては、意味合いとしては「命令」「文」「命令文」などでうまく対応できるのではないかなというのと、「ディレクティブ」という単語は聞き慣れない方も多いのではないかなというのが主な理由です。

**Comment by hanachin** [comment]
[ディレクティブ](http://ja.wikipedia.org/wiki/%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%86%E3%82%A3%E3%83%96)のままでよく聞く気がします。

身近なところだと

- コンパイラディレクティブ
- プリプロセッサディレクティブ
- AngularJSのディレクティブ
- JSPのディレクティブ

言い換えだと指示や宣言でもしっくりくるかなと思います。

- `require_tree`[指示](http://ejje.weblio.jp/content/%E6%8C%87%E7%A4%BA%E6%96%87)
- `require_tree`[宣言](http://ejje.weblio.jp/content/%E5%AE%A3%E8%A8%80)

**Comment by hanachin** [comment]
2.4 マニフェストファイルとディレクティブあたりに`ディレクティブ`の用語の説明があるといいのかもしれません。

**Comment by yasulab** [comment]
> 2.4 マニフェストファイルとディレクティブあたりにディレクティブの用語の説明があるといい

お、確かにディレクティブの初出 (2.4 あたり) で訳注を入れるのが良いかも!

**Comment by hachi8833** [comment]
こちら近々チェックしますね

**Comment by hachi8833** [comment]
遅くなってすみません。
2.4 冒頭に簡単な訳注を追加しました。

**Comment by yasulab** [comment]
確認しました! ありがとうございました :blush:
