### ISSUE TITLE
routing (2.6 コントローラの名前空間とルーティング)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#110]
> This will create a number of routes for each of the `posts` and `comments` controller. For `Admin::PostsController`, Rails will create:

=>

> 上のルーティングにより、`posts`コントローラや`comments`コントローラへのルーティングが多数生成されます。たとえば、`Admin::PostsController`によって作成されるルーティングは以下のとおりです。

ですが、"`Admin::PostsController`によって"という箇所が引っかかります。
"`Admin::PostsController`のために(Railsが)作成するルーティング"という意味ではないでしょうか？(自分の訳は直訳すぎるので、うまい日本語にしていただけるとうれしいです) :)

**Comment by hachi8833** [comment]
訳文修正しました。
