### ISSUE TITLE
routing (4.7 パスを変更する)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#111]
```
Using `scope`, we can alter path names generated by resources:
```
=>
```
`scope`オプションを使用することで、リソースによって生成されたデフォルトのパス名を変更できます。
```
ですが、２点気になりました。

1. ここではscopeはオプションではなくメソッドです
1. この文脈ではresourcesもメソッドとして扱うのが適切な気がします

2つめはメソッドの場合マークダウンの書き方が変わりますので、[本家にPR](https://github.com/rails/rails/pull/19288)しましたので、そちらの結果を見てから必要なら修正したいです。

**Comment by yui-knk** [comment]
書いている側からmergeされました。。。。

**Comment by hanachin** [comment]
:+1:

**Comment by hachi8833** [comment]
https://github.com/rails/rails/blob/master/guides/source/routing.md の修正に合わせて訳を更新しました。
GTT では原文と不一致になりますが、古い訳は今後使われないので問題ないと思います。
