### ISSUE TITLE
active_record_callbacks (全般)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#112]
> コールバックはモデルのリレーションシップを経由して動作できます。また、リレーションシップを使用してコールバックを定義することすらできます。1人のユーザーが多数のポストを持っている状況を例に取ります。あるユーザーが所有するポストは、そのユーザーがdestroyされたらdestroyされる必要があります。

や

> 例として、直前の例に使用したPictureFileモデルで、対応するレコードがdestroyされた後にファイルを1つ削除する必要があるとしましょう。

のように`destroy`がそのままになっている(`削除`と訳さない)のは、`delete`との差を明確にする意図などでしょうか？

**Comment by yasulab** [comment]
:thought_balloon: 引用の場合は code block じゃなくて `> ` による引用の方が見やすいかなと思うので (UI的にもスクロールしないで済むので)、descriptionの記法を少し書き換えてみました :sweat_smile:

**Comment by yui-knk** [comment]
ありがとうございます。今後気をつけます:)

**Comment by hachi8833** [comment]
こちら確認しました。
おそらくご指摘のとおり、destroyとdeleteを訳文で区別する意図だったと思われます。
内容的にはほぼ一律「削除」に置き換えても問題ないと思われますが、念のため現状ママとしようと思います。

**Comment by yui-knk** [comment]
承知しました。closeします
