### ISSUE TITLE
Active Support コア拡張機能(3.7 メソッド委譲)内の誤字

### ISSUE THREAD

**Issue by bata8n** [yasslab/railsguides.jp#113]
>文字列に式展開すると、:toはメソッドが異常されるオブジェクトに対して〜  

とありますが、
>文字列に式展開すると、:toはメソッドが委譲されるオブジェクトに対して〜  

ではないでしょうか？

**Comment by yui-knk** [comment]
@bata8n 修正しました。ご指摘ありがとうございます！
