### ISSUE TITLE
4_1_release_notes(2.2 config/secrets.yml)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#117]
> Rails 4.1 generates a new secrets.yml file in the config folder. デフォルトでは、このファイルにはアプリケーションのsecret_key_baseが含まれていますが、外部API用のアクセスキーなどの秘密キーもここに保存できます。

一行目が原文ママなので、

> Rails 4.1ではconfigディレクトリに新しくsecrets.ymlファイルが作られます。

のような訳をあてるのがいいと思います。

**Comment by hachi8833** [comment]
訳抜け修正しました。
