### ISSUE TITLE
フッターの一部がサイドナビで隠れる

### ISSUE THREAD

**Issue by snaka** [yasslab/railsguides.jp#1173]
OS: macOS 11.6.1（20G224）
Browser: Chrome 97.0.4692.71（Official Build） （x86_64）

で確認したところ、以下のとおりでした。

![image](https://user-images.githubusercontent.com/19329/149252377-9aebfbe8-4bb9-4d5e-ab02-37f5127e3189.png)

**Comment by himajin315** [comment]
修正しました。クローズします 👍 
<img width="1098" alt="スクリーンショット 2022-01-17 10 10 11" src="https://user-images.githubusercontent.com/1221303/149686175-cd23ad3c-0709-4ca1-8d73-7da3058efd04.png">
