### ISSUE TITLE
Rails プラグイン作成入門で.gemspecの修正が必要な点が明記されていない件について

### ISSUE THREAD

**Issue by HiroVodka** [yasslab/railsguides.jp#1177]
https://railsguides.jp/plugins.html

こちらのページに関して、
> 2 新しく生成したプラグインをテストする
プラグインを作成したディレクトリに移動してbundle installコマンドを実行し、自動生成されたテストをbin/testコマンドで実行します。

この状態で`bundle install`を行うと以下のエラー文が表示されます
```
You have one or more invalid gemspecs that need to be fixed.
The gemspec at /plugin名.gemspec is not valid. Please fix this gemspec.
The validation error was 'metadata['homepage_uri'] has invalid link: "TODO"'
```

こちらガイド上に`.gemspec`を修正しなければならない事を追記する必要は無いでしょうか？？

**Comment by yasulab** [comment]
[Edge Guides の方を確認してみました](https://edgeguides.rubyonrails.org/plugins.html#testing-your-newly-generated-plugin)が、特に記載はないようでした！ :eyes: ✅ 

railsguides.jp の Issue としては一旦 Close しますが、原著側にプルリクを送ったらマージされるチャンスかもしれないので、もし気になるようであればぜひチャレンジしてみてください (๑•̀ㅂ•́)و✨

cf. [Railsのドキュメントに貢献する - Railsガイド](https://railsguides.jp/contributing_to_ruby_on_rails.html#rails%E3%81%AE%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E3%81%AB%E8%B2%A2%E7%8C%AE%E3%81%99%E3%82%8B)
