### ISSUE TITLE
api_documentation_guidelines(5 論理値)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#121]
> When "true" or "false" are used as defined in Ruby use regular font. The singletons `true` and `false` need fixed-width font.

=>

> "true"および"false"をRubyの定義どおりに使用する場合は、通常のフォントで表記すること。シングルトンの`true`および`false`は等幅フォントで表記すること。

ですが"シングルトンの"という表現をあまり日本語のドキュメントで見かけないため、以下のように訳注を入れてはどうでしょうか？

> "true"および"false"をRubyの定義どおりに使用する場合は、通常のフォントで表記すること。シングルトンの`true`および`false`は等幅フォントで表記すること(訳注: シングルトンの`true`および`false`とは`TrueClass`および`FalseClass`の唯一のインスタンスのことです)。

http://docs.ruby-lang.org/ja/2.2.0/class/FalseClass.html

**Comment by hachi8833** [comment]
いただいた訳注をそのまま反映いたしました。ありがとうございます!
