### ISSUE TITLE
ブラウザバック時のversionタブの値について

### ISSUE THREAD

**Issue by 00Masato** [yasslab/railsguides.jp#1216]
## 実際の挙動
ヘッダーのバージョン指定タブで過去バージョン（現状、v4.2〜v6.1）を選択。
→Proプラン画面へリダイレクトされる。
→ブラウザバックを行うと、ヘッダーのバージョン指定タブが選択したバージョンの値のままになる。

https://user-images.githubusercontent.com/40224377/159195132-0eefb6f4-b4dd-4b0f-bd6b-70819b979a1f.mov

## 期待される挙動
ブラウザバックを行なった場合、ヘッダーのバージョン指定タブが最新バージョン（現状、v7.0）になっていること

## 環境
OS: mac OS Monterey 12.2.1
ブラウザ: Google Chrome 99.0.4844.83

**Comment by yasulab** [comment]
詳細なフィードバックありがとうございます！(＞人＜ )✨

こちら Chrome 側の仕様に沿って考えると、ブラウザバックする時は、その時の状態（リダイレクトの起点となったバージョン切り替え直後の状態）を保持したままブラウザバックされるのが正しい挙動かなと思いますので、現在の挙動で特に問題ないと考えています 😌（コンテンツの内容も過去バージョンのものではなく、あくまでヘッダーのバージョンの表記のみが直前の状態となっていることも確認いたしました 👀 ✅ ）

特に Pro プランをご利用中の方々にとっては、 **ブラウザバックした後も直前のバージョンを保持したままであることが大切** であるため、Pro プラン利用者の UX を考慮して、こちら一旦 Issue としては Close させていただけたらと考えております。

改めて、詳細なフィードバックありがとうございました！😆 💖
