### ISSUE TITLE
api_documentation_guidelines(5 論理値)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#122]
http://railsguides.jp/api_documentation_guidelines.html#%E8%AB%96%E7%90%86%E5%80%A4

>the user does not need to know which is the actual default value of the flag, and so we only document its boolean semantics.

=>

>上の例では、フラグのデフォルト値の実際の表現がどれであるか (訳注: trueなのか`true`なのかなど) を知る必要はありません。従って、論理値の意味だけをドキュメントに書くべきです。

ですが

> trueなのか`true`なのか

は少々分かりにくいと思います。

> シングルトンのtrueなのか、trueに評価されるオブジェクトなのか

のような書き方に変えてはいかがでしょうか？

**Comment by hachi8833** [comment]
いただいた文に差し替えました。こちらもありがとうございます!
