### ISSUE TITLE
active_record_migrations (3.4 カラムを変更する)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#123]
> Besides `change_column`, the `change_column_null` and `change_column_default` methods are used specifically to change the null and default values of a column.

=>

> `change_column`の他に`change_column_null`メソッドと`change_column_default`メソッドもあり、カラムをnullにしたりデフォルト値を指定したりするのに使用します。

ですが、"カラムをnullにしたり"が気になったので、[原文を修正しました](https://github.com/rails/rails/pull/19454)。
"not null制約を変更したり"のような訳に変更してはいかがでしょうか。

**Comment by hachi8833** [comment]
該当箇所の訳文修正しました。コミットへのリンクがあるととてもやりやすくて助かります。
ありがとうございました!
