### ISSUE TITLE
form_helpers (2.2 フォームとオブジェクトを結び付ける)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#124]
> You can read more about the significance of input names in the parameter_names section.

=>

> input名の重要性については、parameter_namesに関する節を参照してください。

の箇所ですが、`parameter_names`を本家ではlinkに変更しました [PR](https://github.com/rails/rails/pull/19460)。
本家をとりこむときにでも、`パラメータの命名ルールを理解する`などの訳に変えていただきたいです。

**Comment by hachi8833** [comment]
こちら更新時に対応しますね。

**Comment by hachi8833** [comment]
こちらやっぱりリンク修正しました。
