### ISSUE TITLE
[REVIEW] をなくしていく

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#125]
`railsguides.jp/guides/archive/ja`以下のファイルにある`[REVIEW]`を減らしていく。

[see](https://github.com/yasslab/railsguides.jp/wiki/%E7%BF%BB%E8%A8%B3%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8BTIPS#31-%E7%89%B9%E6%AE%8A%E3%82%BF%E3%82%B0%E3%81%BE%E3%81%A8%E3%82%81)

@yasulab  手順としては、"こういう訳にしましょう"もしくは"これこれの理由で今の訳で大丈夫だと思います"というのを１つずつイシューにして、話し合っていく流れでしょうか？

**Comment by yasulab** [comment]
@yui-knk そういった手順でも良いと思いますが、基本的には @hachi8833 さんから上がってきた「(エンジニア視点で) 訳文をレビューして欲しい」という箇所なので、技術的視点でチェックして、必要であれば直接修正/コミットにしちゃってもよいかなとは考えています :ok_hand:

また、問題が無ければ、チェックした旨を commit message で付記した上で `[REVIEW]` を削除する、といった流れを想定しています。

いかがですかね?

**Comment by yui-knk** [comment]
わかりました！　大丈夫だと思います

**Comment by yasulab** [comment]
Idobataでコメントを頂きましたが、こちらにも引用しておきますね。

[![screen shot 2015-03-24 at 13 48 54](https://cloud.githubusercontent.com/assets/155807/6795936/9261f338-d22c-11e4-9271-f5f3cbb92517.png)](https://idobata.io/archives/messages/8461014)

> Review をなくす件、OK です。大丈夫そうならこちらに連絡せずにつぶしていただいてよいです。

**Comment by yasulab** [comment]
こちら、`[REVIEW]`タグがなくなったので閉じますね ;)

```sh
╭─○ yasulab ‹2.4.0› ~/railsguides.jp/guides/source/ja
╰─○ grep -r "\[REVIEW\]" ./                                                                japanese ✓ ±
╭─○ yasulab ‹2.4.0› ~/railsguides.jp/guides/source/ja
╰─○                                                                                        japanese ✓ ±
```
