### ISSUE TITLE
active_record_migrations (3.4 カラムを変更する)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#126]
> This sets `:name` field on products to a `NOT NULL` column and the default value of the `:approved` field to false.

=> 

> [REVIEW]上のマイグレーションはproductsテーブルの`:name`フィールドを`NOT NULL`カラムに設定し、`:approved`フィールドのデフォルト値をfalseに設定します。

#123 に関連して、"上のマイグレーションはproductsテーブルの`:name`フィールドに`NOT NULL`制約を設定し"　のように修正して、REVIEW済みとしてはどうでしょうか。

**Comment by hachi8833** [comment]
修正反映し、REVIEW終了としました。ありがとうございます!
