### ISSUE TITLE
ActionCableのガイドでJSのシンタックスハイライトが効いていない

### ISSUE THREAD

**Issue by okuramasafumi** [yasslab/railsguides.jp#1276]
https://railsguides.jp/action_cable_overview.html

`.js`のファイルがシンタックスハイライトが効いていない状態になっています。
このページ以外は未確認ですが、他にもまだあるかもしれません。

**Comment by yasulab** [comment]
報告ありがとうございます！後ほど確認してみますね...!! 👀💨✨
