### ISSUE TITLE
active_support_core_extensions (2.13 警告・ストリーム・例外の抑制)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#128]
> Silencing exceptions is also possible with `suppress`. This method receives an arbitrary number of exception classes. If an exception is raised during the execution of the block and is `kind_of?` any of the arguments, `suppress` captures it and returns silently. Otherwise the exception is reraised:

=>

> `suppress`メソッドを使用すると例外の発生を止めることもできます。このメソッドは、例外クラスを表す任意の数値を受け取ります。[REVIEW]`suppress`は、あるブロックの実行時に例外が発生し、その例外が(`kind_of?`による判定で)いずれかの引数に一致する場合、それをキャプチャして例外を発生せずに戻ります。一致しない場合、あらためて例外を発生します。

[こちらを参照](https://github.com/rails/rails/blob/v4.2.1/activesupport/lib/active_support/core_ext/kernel/reporting.rb#L68).

1. "このメソッドは、例外クラスを表す任意の数値を受け取ります。"は"このメソッドは引数に、任意の数の例外クラスを受け取ります。"が正しいと思います。

2. "Otherwise the exception is reraised"ですが、実装を読んだところ正確には"not captured"だと思います。こちらは原著にPRします。

**Comment by yui-knk** [comment]
原文[修正しました](https://github.com/rails/rails/pull/19610)

**Comment by yasulab** [comment]
リンクが `(hogehoge)[http://...]` となっていたので (丸括弧と角括弧が逆になっていたので) 修正したのですが、これって意図的なんでしょうか? :sweat_drops: 

:thought_balloon: ちなみに原文修正も同じような感じになっておりました :sweat:

**Comment by yui-knk** [comment]
え、どの箇所でしょうか？

**Comment by yui-knk** [comment]
> 原文修正

19610のcommitメッセージですか？
でしたら、僕のミスです。意図はありません :cry:

**Comment by yasulab** [comment]
> 19610のcommitメッセージですか？
リンク先の Pull Request の description の括弧が逆になっていたのですが、もう直ってますね :sweat_smile: 

> でしたら、僕のミスです。意図はありません :cry:
いえいえ! 何か意図があれば聞いておきたい、ぐらいの感覚でした :sweat_drops: 

Issue 立てありがとうございます :smile_cat:

**Comment by hachi8833** [comment]
2点修正いたしました。ありがとうございます! 

FYI:
本家は Github上では直ってますが
http://guides.rubyonrails.org/active_support_core_extensions.html はまだですね。

2つ目の Not captured の方ですが、古い原文に修正訳を入れています。原文が新しくなれば次回は使われないセグメントなので影響はないと思います。

**Comment by yui-knk** [comment]
@hachi8833  こちら、`[REVIEW]`が残っているは、外し忘れでしょうか？

**Comment by hachi8833** [comment]
あ、すみません、修正します

**Comment by hachi8833** [comment]
削除しました
