### ISSUE TITLE
active_support_core_extensions (3.2.1 alias_attribute)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#129]
> As in other aliasing methods, the new name is the first argument, and the old name is the second (my mnemonic is they go in the same order as if you did an assignment):

=>

> 他の別名作成メソッドと同様、1つ目の引数には新しい名前、2つ目の引数には元の名前を指定します ([REVIEW]割り当てを行ったのと同様に、指定と同じ順序でエイリアスが作成されるはずです)。

この括弧のなかですが、old nameとnew nameの順番の覚え方(mnemonic)として、変数に代入(assignment)するのと同じ順番 (new_name = old_name)。という意味ではないでしょうか？

**Comment by hachi8833** [comment]
修正しました。ありがとうございます!
