### ISSUE TITLE
active_support_core_extensions (5.10.12 constantize)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#133]
> So, it is in general not equivalent to what Ruby would do in the same spot, had a real constant be evaluated.

=>

> [REVIEW]従って、一般的にはこのメソッドは、Rubyが同じ場所 (評価される実際の定数がある) に対して行なうものと等価ではありません。

"had a real constant be evaluated"ですが、"その場所でRubyが定数を評価したときの値"というニュアンスではないでしょうか。下記のコードでいうと、`X # => :in_M`のケースに相当します。

```ruby
X = :in_Object
module M
  X = :in_M
 
  X                 # => :in_M
  "::X".constantize # => :in_Object
  "X".constantize   # => :in_Object (!)
end
```

"従って、このメソッドは、同じ場所でRubyが定数を評価したときの値と必ずしも等価ではありません。"のような訳がいいのではないでしょうか。

**Comment by hachi8833** [comment]
いただいた修正訳に置き換えました。ありがとうございます!
