### ISSUE TITLE
Active Record マイグレーション の 外部キー の説明においてテーブル名が間違っている

### ISSUE THREAD

**Issue by abe4tawa8** [yasslab/railsguides.jp#134]
Ruby on Rails Guides 公式サイトの Active Record Migrations の説明では `authors` テーブルとなっているところが、こちらのリポジトリの `japanese` ブランチおよび `master` ブランチ共に `articles` テーブルになっています。

## rails/docrails

https://github.com/rails/docrails/blob/master/guides/source/active_record_migrations.md
> This adds a new foreign key to the author_id column of the articles table. The key references the id column of the authors table.

## Ruby on Rails Guides
http://guides.rubyonrails.org/active_record_migrations.html#foreign-keys

### 日本語
https://github.com/yasslab/railsguides.jp/blob/japanese/guides/source/active_record_migrations.md
> 上によって新たな外部キーがarticlesテーブルのauthor_idカラムに追加されます。このキーはarticlesテーブルのidカラムを参照します。

### 英語
https://github.com/yasslab/railsguides.jp/blob/master/guides/source/active_record_migrations.md
> This adds a new foreign key to the author_id column of the articles table. The key references the id column of the articles table.

## 関連コミット

- [AR Migrations Guide#Foreign Keys: fix wrong table · rails/docrails@2a1afe6](https://github.com/rails/docrails/commit/2a1afe6b372b9c8c59b875ebaa0e4f29e407afc2)

**Comment by hachi8833** [comment]
こちら、現状に合わせて訳文のみ修正しました。

(この箇所は原文と訳文が食い違うことになりますが、今後更新するときはこのセグメントは使われないはずなので、"The key references the id column of the articles table." が今後まったく正しいコンテキストで使用されるようなことでもない限りたいてい大丈夫だと思います)
