### ISSUE TITLE
active_support_core_extensions (14.1 bind)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#135]
`Proc#bind`が4.1で[削除されました](http://railsguides.jp/4_1_release_notes.html#active-support-%E5%89%8A%E9%99%A4%E3%81%95%E3%82%8C%E3%81%9F%E3%82%82%E3%81%AE)。

本家には[PR](https://github.com/rails/rails/pull/19662)をだしましたので、採用されたら記述を削除しますか？

**Comment by yui-knk** [comment]
mergeされました

**Comment by yasulab** [comment]
おぉ、PRありがとうございます :smile: 

採用されたようなので、該当箇所を削除しておきますね :construction_worker:

**Comment by yasulab** [comment]
:thought_balloon: 年度始めのドタバタで他のIssueはまだチェックできていませんが、順次チェックしていきますね :white_check_mark:

**Comment by yasulab** [comment]
@yui-knk ...と思って手を動かそうとしたんですが、せっかく翻訳メモリに入った「原文-訳文」のデータを削除するのももったいない (加えて、GTTで訳文を空にすると、「原文-訳文(空)」の間違ったペアが翻訳メモリに格納されてしまう問題もあります) ので、次のセクションまで無視するタグを実装するとよいかなぁと思ったんですが、いかがでしょうか?

**Comment by yui-knk** [comment]
@yasulab このPRに関して言えば、"次のセクションまで無視するタグ"などで対応するのがいいと思います。

現在、GTTの原文を更新していないので、Proc#bindを削除するのはGTTの原文を更新するタイミングでもいいと思います。
このあたり、原文をどのタイミングで更新するかとか、ことなるrails guideのバージョンをどう管理するか、とか決めないといけない気がします。。。。

**Comment by yasulab** [comment]
> 現在、GTTの原文を更新していないので、Proc#bindを削除するのはGTTの原文を更新するタイミングでもいいと思います。

なるほど、了解です。では、原文を更新するタイミングで対応しましょう。



> このあたり、原文をどのタイミングで更新するかとか、ことなるrails guideのバージョンをどう管理するか、とか決めないといけない気がします。。。。

ですね。GTTは翻訳時にはとても便利ですが、バージョン管理機能が備わっていないので、もっと細かく管理したいときに問題があるんですよね... :sweat: 

現在はGTTに依存していますが、最終的にはうまくGTTから卒業 (もしくは疎結合にする感じ) にできたらなぁと考えております。

**Comment by hachi8833** [comment]
今、active_support_core_extensionsの最新版をGTTで更新してみています

**Comment by hachi8833** [comment]
GTTで更新終わったので今共有しました。
(結局一日仕事になってしまった...)

**Comment by yui-knk** [comment]
Fixed by 5fc461997a2f63bdcf078c9ffcddbee5f60b1e1b
