### ISSUE TITLE
active_support_core_extensions (9.2 index_by)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#136]
> The method `index_by` generates a hash with the elements of an enumerable indexed by some key.
It iterates through the collection and passes each element to a block. The element will be keyed by the value returned by the block:

=> 

> [REVIEW]`index_by`メソッドは、何らかのキーによってインデックス化されたenumerableの要素を持つハッシュを生成します。
このメソッドはコレクションを列挙し、各要素をブロックに渡します。この要素は、ブロックから返された値によってキーとなります。

REVIEWのほうの行は問題ないと思います。２行目ですが、"キーとなります"という表現がひっかかります。以下のような訳はどうでしょうか？

1. "このメソッドはコレクションを列挙し、各要素をブロックに渡します。ブロックの戻り値をキー、要素を値とするハッシュを生成します。"

  意訳です。

1. "このメソッドはコレクションを列挙し、各要素をブロックに渡します。この要素は、ブロックから返された値によってインデックス化されます。"

  "will be keyed"を"will be indexed"と読みかえて訳しています。

**Comment by hachi8833** [comment]
「インデックス化」で修正しました。ありがとうございます!
