### ISSUE TITLE
Active Record バリデーション の validates_each の説明文がおかしい

### ISSUE THREAD

**Issue by abe4tawa8** [yasslab/railsguides.jp#137]
「Active Record バリデーション」の「2.13 validates_each」において、「属性の名前」が連続して出てきています。
同ファイル内に「属性の値」という表現があることから、こちらもそのように修正されるのがよろしいのではないでしょうか。

## yasslab/railsguides.jp
https://github.com/yasslab/railsguides.jp/blob/b1194e3191d1d8c969fe8a10e39af0f5862739f5/guides/source/active_record_validations.md
> このブロックは、レコードと属性の名前、そして属性の名前を受け取ります。

## rails/docrails
https://github.com/rails/docrails/blob/c1a1c58a93305e3fe46d1fa9c1eea73b899449c0/guides/source/active_record_validations.md
> The block receives the record, the attribute's name and the attribute's value.

**Comment by yui-knk** [comment]
@abe4tawa8  ご指摘ありがとうございました。修正しました！

**Comment by abe4tawa8** [comment]
@yui-knk ご対応ありがとうございました。
