### ISSUE TITLE
Active Record バリデーション の errors.clear の説明文がおかしい

### ISSUE THREAD

**Issue by abe4tawa8** [yasslab/railsguides.jp#138]
「Active Record バリデーション」の「7.5 errors.clear」を読んだ際に、 `valid?` メソッドについて誤解を与えかねない表現があると感じました。
その理由は、「`valid?`などのオブジェクトをデータベースに保存しようとするメソッド」と書かれてあるため、あたかも `valid?` メソッドにオブジェクトをデータベースに保存する動きがあるかのように解釈する人が出るのではないかと感じたためです。あくまでも私の感覚ですが。

ソース | 文
--- | ---
原文 | `valid?` or any method that tries to save this object to the database
日本語訳 | `valid?`などのオブジェクトをデータベースに保存しようとするメソッド
私訳 | `valid?`やオブジェクトをデータベースに保存しようとするメソッド

## yasslab/railsguides.jp
https://github.com/yasslab/railsguides.jp/blob/b1194e3191d1d8c969fe8a10e39af0f5862739f5/guides/source/active_record_validations.md
> `valid?`などのオブジェクトをデータベースに保存しようとするメソッドが次回呼び出されたときに、バリデーションが再実行されます。

## rails/docrails
https://github.com/rails/docrails/blob/c1a1c58a93305e3fe46d1fa9c1eea73b899449c0/guides/source/active_record_validations.md
> but the next time you call `valid?` or any method that tries to save this object to the database, the validations will run again.

**Comment by yui-knk** [comment]
@abe4tawa8 こちらも対応しました。ありがとうございました

**Comment by abe4tawa8** [comment]
@yui-knk ご対応ありがとうございました。
