### ISSUE TITLE
「Action View の概要」で訳文ミス

### ISSUE THREAD

**Issue by fugaco** [yasslab/railsguides.jp#139]
Action View の概要
http://railsguides.jp/action_view_overview.html

> なお、Webページへの出力結果の最初と最後からホワイトスペースを取り除きたい場合は<%- -%>を通常の<% and %>と交互にご使用ください (訳注: これは英語のようなスペース分かち書きを行なう言語向けのノウハウです)。

上記の `<% and %>` は `<% %>` あるいは `<% や %>` の間違いだと思われます。

**Comment by hachi8833** [comment]
こちらも修正しました。
