### ISSUE TITLE
active_support_core_extensions (17.2 Time Constructors)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#140]
> Active Support defines `Time.current` to be `Time.zone.now` if there's a user time zone defined, with fallback to `Time.now`:

=>

> [REVIEW]Active Supportは、`Time.current`の値が`Time.zone.now`の値と同じになるように定義しています。ユーザータイムゾーンが定義されていれば`Time.now`と同じになります。

ですが、２点気になりました。

1. "if there's a user time zone defined"のかかる先がズレている

  ユーザータイムゾーンが定義されていれば、`Time.zone.now`を返します。

1. fallbackの訳が間違っている

  ユーザータイムゾーンが定義されていなければ、`Time.now`を返します。

ですので、次のような訳がいいかと思います。

> ユーザータイムゾーンが定義されているとき、Active Supportは、`Time.current`の値が`Time.zone.now`の値と同じになるように定義しています。ユーザータイムゾーンが定義されていなければ`Time.now`と同じになります。

[cf: コード](https://github.com/rails/rails/blob/v4.2.1/activesupport/lib/active_support/core_ext/time/calculations.rb#L29)

**Comment by hachi8833** [comment]
ありがとうございます。今core_extensionの流し込みやってるので、そちらに反映します。

**Comment by hachi8833** [comment]
新しい方で修正しました。

**Comment by yui-knk** [comment]
Fixed by 5fc461997a2f63bdcf078c9ffcddbee5f60b1e1b
