### ISSUE TITLE
railsguides.jp のversion管理について(原文更新時にedgeが入ってしまう)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#145]
@yasulab 
[こちらのcommit](https://github.com/yasslab/railsguides.jp/commit/5fc461997a2f63bdcf078c9ffcddbee5f60b1e1b)をしたときに、`Enumerable#without`の説明が追加されました。
よく調べたらこのメソッドは[master](https://github.com/rails/rails/commit/c7a37c10ade8372c712be01a7e4ddbe8785c5139)にしか入っていないようなんですが、どうしたらいいでしょうか。
すみません。

**Comment by yasulab** [comment]
すみません、 #141 の作業がまだ全然進められていないので、現状では同様のコミットを `japanese` ブランチでもコミットしかないかなと考えています :sweat_drops:

**Comment by yui-knk** [comment]
わかりました！
引き続き`japanese`のブランチにcommitをいれていきますね

**Comment by yasulab** [comment]
よろしくお願いします! 
(本家のコミットをチェックしてくれる人がいて本当助かっております :bow: )

**Comment by yui-knk** [comment]
本家も複数ブランチ(master, 4_2_stableなど)でguideを管理しているので、こちらも理想的には、複数branchで管理したいですねー。

**Comment by yasulab** [comment]
おぉ、確かにそうですね :) 現状では最新に追いつくので手一杯ですが、最終的には同じ構成にしていきたいですね :smile:
