### ISSUE TITLE
active_support_core_extensions (3.1 alias_method_chain)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#147]
>  # save a reference to the original process method alias_method :original_process, :process

=>

>  # 参照を元のプロセスメソッドalias_method :original_process, :processへ保存

の箇所ですが、`alias_method :original_process, :process`はrubyのコードです。
`元のprocessメソッドへの参照を保存する[改行]rubyのコード`のように修正するのがいいと思います。
改行がうまく機能していないようですね。

**Comment by hachi8833** [comment]
こちらはprepミスでした。ここだけセグメンテーションを変えるわけにもいかないので、最新ソースから流し込んでみます(ああ、また時間がかかる...)
