### ISSUE TITLE
active_support_core_extensions (10.1 Accessing1)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#148]
> second、third、fourth、fifthは、対応する位置の要素を返します (firstは元からビルトインされています)。社会の智慧と建設的な姿勢のおかげで、今ではforty_twoも使用できます (訳注: これは何らかのジョークの可能性、実際にはforty_twoは使用できない)。

の訳注ですが。

少なくとも4.2.1では[実装されていました・・・](https://github.com/rails/rails/blob/v4.2.1/activesupport/lib/active_support/core_ext/array/access.rb#L61)

**Comment by yasulab** [comment]
おぉ、この実装初めて知りました!! :sweat_smile: 

Easter Egg 的で面白いですねw

**Comment by yasulab** [comment]
`forty_two`が使えるバージョンと使えないバージョンがあると思うので、`Rails x.x.x より使用可能` といった訳注にするとよさそうですね :+1:

**Comment by hanachin** [comment]
[生命、宇宙、そして万物についての究極の疑問の答え](http://ja.wikipedia.org/wiki/%E7%94%9F%E5%91%BD%E3%80%81%E5%AE%87%E5%AE%99%E3%80%81%E3%81%9D%E3%81%97%E3%81%A6%E4%B8%87%E7%89%A9%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6%E3%81%AE%E7%A9%B6%E6%A5%B5%E3%81%AE%E7%96%91%E5%95%8F%E3%81%AE%E7%AD%94%E3%81%88)です。

**Comment by hanachin** [comment]
[このコミット](https://github.com/rails/rails/commit/9d8cc60ec3845fa3e6f9292a65b119fe4f619f7e)で導入されました。
Rails 2.2以降であれば使えます。

**Comment by hanachin** [comment]
> Also known as accessing "the reddit".

やRailsガイド中の

> 社会の智慧と建設的な姿勢のおかげで、今ではforty_twoも使用できます

は実装された経緯によるものです。

[Why is Array.forty_two() called "the reddit" in Ruby on Rails? - Quora](http://www.quora.com/Why-is-Array-forty_two-called-the-reddit-in-Ruby-on-Rails)

訳注難しそう :sweat_smile:

**Comment by yasulab** [comment]
こんな感じの訳注を考えてみました。

>  (訳注: [Rails 2.2 以降](https://github.com/rails/rails/commit/9d8cc60ec3845fa3e6f9292a65b119fe4f619f7e)で使えます。詳細は Quora の [Why is Array.forty_two() called "the reddit" in Ruby on Rails?](http://www.quora.com/Why-is-Array-forty_two-called-the-reddit-in-Ruby-on-Rails) を参照してください)。

**Comment by yasulab** [comment]
代案

> (訳注: [Rails 2.2 以降](https://github.com/rails/rails/commit/9d8cc60ec3845fa3e6f9292a65b119fe4f619f7e)で使えます。「42」については、Wikipediaの[生命、宇宙、そして万物についての究極の疑問の答え](http://ja.wikipedia.org/wiki/%E7%94%9F%E5%91%BD%E3%80%81%E5%AE%87%E5%AE%99%E3%80%81%E3%81%9D%E3%81%97%E3%81%A6%E4%B8%87%E7%89%A9%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6%E3%81%AE%E7%A9%B6%E6%A5%B5%E3%81%AE%E7%96%91%E5%95%8F%E3%81%AE%E7%AD%94%E3%81%88) を参照してください)

**Comment by yui-knk** [comment]
LGTM!
