### ISSUE TITLE
ルーティングの2.10.3の和訳について

### ISSUE THREAD

**Issue by bisque33** [yasslab/railsguides.jp#150]
すごく細かいことで恐縮ですが、読んでいて気になる部分がありましたのでご連絡いたします。

[ルーティング](http://railsguides.jp/routing.html)の2.10.3を読んで、:onオプションを使つかうとnew以外でもアクションを追加できるのかなと思ったんですが、原文やソースコードを読むと追加できるのはnewアクションだけということでした。（なぜnewアクションだけなのかは説明されていないので分からないのですが。）

なので、和訳を以下のように修正してはどうでしょうか。

原文: 2.10.3 Adding Routes for Additional New Actions
和訳(現在): 2.10.3 追加されたアクションへのルーティングを追加する
和訳(修正): 2.10.3 追加されたnewアクションへのルーティングを追加する

原文: To add an alternate new action using the :on shortcut:
和訳(現在): :onショートカットを使用して、たとえば以下のように別のnewアクションを追加できます。
和訳(修正): :onオプションを使用して、たとえば以下のように別のnewアクションを追加できます。

shortcutが意味するのはおそらく「:onを使えば短縮して書ける」ということだと思いますので、和訳には出さなくても良いかと思います。

以上です。良ければ「翻訳の流れ」に沿って、プルリクをしてみようと思いますので、お手数ですがご確認のほどお願いいたします。

**Comment by hachi8833** [comment]
ご指摘の2点を修正しました。ありがとうございます!

**Comment by bisque33** [comment]
お手数をお掛けしました。こちらこそありがとうございました！
