### ISSUE TITLE
Footerに各記事の一覧を設置したい

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#151]
現状だと各記事へのページ遷移したり、他のページの存在を知るためには、

1. 「 `ガイド目次` をクリックする」
2. 「ロゴなどをクリックする (トップページへ移動する)」

などのアクションをしないといけない。

Railsガイドには多くの有用な記事があることを、できるだけ多くの読者に知ってもらいたいので、Footerに各記事へのサイトマップがあると良いのではないかな...と考えております :bow: 

![footer](https://cloud.githubusercontent.com/assets/155807/7529731/04624596-f578-11e4-8a6a-36b5c47ce9ee.png)

:thought_balloon: @himajin315 さんあたりにデザインしてもらえないかな... (チラッ

**Comment by himajin315** [comment]
簡単に３列に分けて表示させるようにしました。どうでしょうか。

![2015-05-08 18 47 32](https://cloud.githubusercontent.com/assets/1221303/7534182/0b5b40f6-f5b3-11e4-870d-aa199a533af9.png)

**Comment by yasulab** [comment]
@himajin315 おぉ! PRあざす！

モバイル版って対応されてます？
