### ISSUE TITLE
testing (3 モデルに対する単体テスト)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#152]
> In Rails, models tests are what you write to test your models.

=> 

> [REVIEW]Railsにおけるモデルのテストとは、モデルをテストするために書いたコードを指します。

の箇所ですが、その後原文で[修正](https://github.com/rails/rails/commit/7514b6ab)が入っています。
(その後[削除](https://github.com/rails/rails/commit/afbd6559f98b2166ba4c1f3dec52a33f10c2a827)されていますが)

この修正をふまえた訳に修正していいでしょうか？

例：`Railsにおけるユニットテストとは、モデルをテストするために書いたコードを指します。`

**Comment by yasulab** [comment]
> この修正をふまえた訳に修正していいでしょうか？

[REVIEW の文については適宜修正しちゃって大丈夫](https://idobata.io/archives/organization/yasslab/room/railsguides/2015-03-24)という話だったと思うので、僕は良いんじゃないかと思います! :ok:

**Comment by yui-knk** [comment]
承知しました！

**Comment by yasulab** [comment]
@yui-knk 今 @hanachin さんに #141 の作業をしてもらってるんですが (cf. https://github.com/yasslab/railsguides.jp/pull/154 )、作業途中で `japanese` ブランチにコミットされてしまう conflict が起こって手戻り作業が発生してしまうようなので、 @hanachin さんの作業が終わるまでコミットは控えてもらえると助かります :bow:  :sweat_drops:

**Comment by yui-knk** [comment]
@yasulab  承知です！

**Comment by hanachin** [comment]
おまたせしてすみません、 https://github.com/yasslab/railsguides.jp/pull/161 でプルリクエストしました。

**Comment by yasulab** [comment]
ロックかけちゃってすみません :bow: 

無事に merge されたので、いつでもコミットして大丈夫です :ok_hand: 

また、 #141 の解決に伴い、(原著と訳著が同じリポジトリで管理できるようになって) ディレクトリ構成が少し変わったので、その点にはお気をつけください :construction_worker:
