### ISSUE TITLE
testing (3 モデルに対する単体テスト)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#153]
> NOTE: The method name is generated by replacing spaces with underscores. The result does not need to be a valid Ruby identifier though, the name may contain punctuation characters etc. That's because in Ruby technically any string may be a method name. Odd ones need `define_method` and `send` calls, but formally there's no restriction.

=>

> メモ: テスト名からのメソッド名生成は、スペースをアンダースコアに置き換えることによって行われます。[REVIEW]生成されたメソッド名はRubyの正規な識別子である必要はありませんが、テスト名にはパンクチュエーションなどの文字を含めることができます。これが可能なのは、Rubyがメソッド名にあらゆる文字列を使用できるからです。`define_method`や`send`のように一見問題の起きそうな呼び出しが必要になることがあるかもしれません。しかし名前の付け方には公式な制限はありません。

1. "正規な識別子"に関しては問題ないと思います[see](http://docs.ruby-lang.org/ja/2.2.0/doc/spec=2flexical.html#identifier)
1. パンクチュエーションに関しては注釈で"句読点"、もしくは".,など"と補ったほうがいいと思います
1. "正規な識別子である必要はありませんが"の"が"は不要だと思います。"The result does not need to be a valid Ruby identifier"全体に"though"がかかっているものだと思います。
1. "Odd ones need"の箇所は`define_method :"test.t"`のような呼び方が必要になることを指しているのではないでしょうか？

## 背景

[railsのコード](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/testing/declarative.rb)を読むと、`to_sym`してから`define_method`しているため句読点を含むメソッド名でも問題ないようです。

```ruby
[4] pry(main)> "test.t".to_sym
=> :"test.t"
[6] pry(main)> My.send(:define_method, :"test.t") {}
=> :"test.t"
[7] pry(main)> ls My
My#methods: test.t
```

**Comment by hachi8833** [comment]
返信遅れてすみません。ご指摘の箇所修正しました。

**Comment by yui-knk** [comment]
ありがとうございます。反映します！
