### ISSUE TITLE
各記事に Tweet / Like / はてブボタンを設置する?

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#162]
:thought_balloon: 各記事の見出しの直後に Social ボタン (Tweet / Like / はてブボタン) があると良いのではないかなぁという意見を頂きました。

> Ruby on Rails ガイド：体系的に Rails を学ぼう (Rails 4.2 対応) http://railsguides.jp/  #Railsガイド
> 各ページにツイートボタンつけてくれないかなー。 

cf. https://twitter.com/naichilab/status/598325651569971200
## イメージ図

:thought_balloon: こんな感じかな?

![screen shot 2015-05-13 at 13 06 21](https://cloud.githubusercontent.com/assets/155807/7603589/ffd2136a-f970-11e4-8655-aa574d206453.png)

**Comment by hanachin** [comment]
- 読み込み速度が遅くならないか
- モバイル版の見た目に影響でないか

あたりが気になりますね
