### ISSUE TITLE
「Active Model の基礎」に欠落している部分がある

### ISSUE THREAD

**Issue by wakairo** [yasslab/railsguides.jp#1687]
「Active Model の基礎」について、[本家の英語のRails Guides](https://guides.rubyonrails.org/v7.2/active_model_basics.html)と比べると無くなっている部分があります。

具体的には、[英語にはある以下の部分](https://github.com/rails/rails/blob/main/guides/source/active_model_basics.md?plain=1#L391C1-L435C4)が、日本語には見当たりません。

If you call a method that is not defined, it will raise a `NoMethodError` error.

#### Method: `alias_attribute`

`ActiveModel::AttributeMethods` provides aliasing of attribute methods using
`alias_attribute`.

The example below creates an alias attribute for `name` called `full_name`. They
return the same value, but the alias `full_name` better reflects that the
attribute includes a first name and last name.

```ruby
class Person
  include ActiveModel::AttributeMethods

  attribute_method_suffix "_short?"
  define_attribute_methods :name

  attr_accessor :name

  alias_attribute :full_name, :name

  private
    def attribute_short?(attribute)
      public_send(attribute).length < 5
    end
end
```

```irb
irb> person = Person.new
irb> person.name = "Joe Doe"
irb> person.name
=> "Joe Doe"

# `full_name` is the alias for `name`, and returns the same value
irb> person.full_name
=> "Joe Doe"
irb> person.name_short?
=> false

# `full_name_short?` is the alias for `name_short?`, and returns the same value
irb> person.full_name_short?
=> false
```

**Comment by hachi8833** [comment]
@wakairo ご指摘ありがとうございます！🙇
こちら修正します。
