### ISSUE TITLE
form_helpers (1.1 一般的な検索フォーム)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#169]
> For every form input, an ID attribute is generated from its name ("q" in the example).

=> 

> どのフォームinputを使用した場合でも、id属性はフォームの名前から生成されます (上の例では「q」)。

"id属性はその名前(もしくはname属性)から生成されます"の誤りだと思います。"from"を"form"として訳しているように感じます。

**Comment by hachi8833** [comment]
修正しました。

**Comment by yui-knk** [comment]
ありがとうございました１
