### ISSUE TITLE
form_helpers (1.3.1 チェックボックス / 1.3.2 ラジオボタン)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#170]
> The first parameter to `check_box_tag`, of course, is the name of the input. The second parameter, naturally, is the value of the input.

=>

> `check_box_tag`の最初のパラメータは、言うまでもなくinputの名前です。2番目のパラメータには、ご想像のとおりinputの値が使用されます。

および

> As with `check_box_tag`, the second parameter to `radio_button_tag` is the value of the input.

=>

> `check_box_tag`ヘルパーのときと同様、`radio_button_tag`の2番目のパラメータにはinputの値が使用されます。

どちらも、２番目のパラメータがinput(タグ)のvalue属性になるという意味だと思います。

**Comment by hachi8833** [comment]
ご指摘ありがとうございます! 修正してみました。
