### ISSUE TITLE
原著の間違え @ Development Dependencies Install

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#174]
![screen shot 2015-06-01 at 13 42 59](https://cloud.githubusercontent.com/assets/155807/7906332/358c84b6-0864-11e5-9d37-f08b9839b9b3.png)

**Comment by yui-knk** [comment]
[master](https://github.com/rails/rails/blob/master/guides/source/contributing_to_ruby_on_rails.md)
ではきえてますね

**Comment by yui-knk** [comment]
とおもったら、[こっち](https://github.com/rails/rails/blob/master/guides/source/development_dependencies_install.md#the-hard-way)にうつっている

**Comment by yui-knk** [comment]
https://github.com/rails/rails/pull/20393

PRed

**Comment by yasulab** [comment]
Thx! :+1:

**Comment by yui-knk** [comment]
merged!
