### ISSUE TITLE
action_view_overview (3 テンプレート、パーシャル、レイアウト)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#176]
> As mentioned before, the final HTML output is a composition of three Rails elements: `Templates`, `Partials` and `Layouts`.

=>

> 前述のとおり、Railsが出力する最終的なHTMLは`テンプレート`、`パーシャル`、`レイアウト`の3つの要素です。

ですが、

> 前述のとおり、Railsが出力する最終的なHTMLは`テンプレート`、`パーシャル`、`レイアウト`の3つのRailsの要素から成ります。

の方が適切ではないでしょうか？

**Comment by yasulab** [comment]
> の3つのRailsの

`の`が３回以上続くと読みづらくなるのと、`Railsが出力する...`とRailsに関する要素であることは言及されているので、`Railsの`を削除して適用しますね :+1:

**Comment by yasulab** [comment]
また、Compenentの訳が`要素`と`コンポーネント`とでバラついていたので、(要素の方が多かったので) `要素`に統一しておきました :wrench:
