### ISSUE TITLE
action_view_overview (3.1.2 Builderテンプレート)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#177]
> An XmlMarkup object named `xml` is automatically made available to templates with a `.builder` extension.

=>

> たとえば、`xml`という名前のXmlMarkupオブジェクトを使用すると、自動的に拡張子`.builder`のテンプレートが適用されます。

ですが

> テンプレートの拡張子を`.builder`にすると、`xml`という名前のXmlMarkupオブジェクトが自動で使用可能になります。

のほうがよいと思います。

**Comment by yasulab** [comment]
訳文では`使用可能`より`使用できる`といった文体が多いので、そちらに微調整して取り込んでみます! :ok_hand:
