### ISSUE TITLE
action_view_overview (3.2.2 パーシャルを活用してビューを簡潔に保つ)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#178]
> One way to use partials is to treat them as the equivalent of subroutines; a way to move details out of a view so that you can grasp what's going on more easily. For example, you might have a view that looks like this:

=>

> すぐに思い付くパーシャルの使い方といえば、パーシャルをサブルーチンと同等のものとみなすというのがあります。ビューの詳細部分をパーシャルに移動し、コードの見通しを良くするために、たとえば、以下のようなビューがあるとします。

ですが、`For example`の前で文が終わっているので、以下のように訳したほうがいいと思います。

> すぐに思い付くパーシャルの使い方といえば、パーシャルをサブルーチンと同等のものとみなすというのがあります。ビューの詳細部分をパーシャルに移動し、コードの見通しを良くするために、パーシャルを使うのです。たとえば、以下のようなビューがあるとします。

**Comment by yasulab** [comment]
提案ありがとうございます! こちら、途中で訳がきれていたみたいですね :sweat_drops: 頂いた文をそのまま採用させていただきますね :+1:
