### ISSUE TITLE
GTTから `archive.zip` をダウンロードできるスクリプトを作成する

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#180]
途中までは書いてあるんですが、まだ完成していない :sweat: 
https://github.com/yasslab/railsguides.jp/blob/japanese/guides/download_archive.coffee

:thought_balloon: Rakeとして足したほうがいいかも?

cc/ @hanachin

**Comment by yasulab** [comment]
@hanachin says:

> ダウンロードする対象のファイルはラベルを元に判断しているので、新しいファイルが追加されたときにラベルを交換したりする部分が結局手作業として残ってしまうので、それが問題ですね。
> 
> ラベルつけ忘れたり、別のファイルにラベルをつけたりといった間違いが起きやすいので。
> 
> アップロードする際のファイル名に「何のプロジェクトか」「どのバージョンか」みたいなのを付与して、ファイル名を元に選択出来れば、ラベルを付ける作業減らせてよさそうです

**Comment by hanachin** [comment]
> https://github.com/yasslab/railsguides.jp/blob/japanese/guides/download_archive.coffee

用途としてはGTTにアクセス出来る人がarchive.zipをCLIからDL出来るように書いたので、「誰でも」用ではないですね。確認したところ動いていなかったのでRakeタスクで置き換えておきます。

**Comment by hanachin** [comment]
現状だと、GTTからダウンロードした最新版のarchive.zipがリポジトリに含まれているので「誰でも」GTTからダウンロード出来るようにする必要はないのかなぁという認識です。

**Comment by yasulab** [comment]
> 確認したところ動いていなかったのでRakeタスクで置き換えておきます。

こちら、「とりあえず Rails チュートリアルのスクリプトを拝借しただけ」って感じで、まだRailsガイド用にはなっていないって認識です :sweat: 

> 「誰でも」GTTからダウンロード出来るようにする必要はないのかなぁ

IDやPASSを公開せずに、READ ONLY で誰でも GTT から `archive.zip` をダウンロードできるとよさそうかなって考えていたんだけれど、ちょっと具体的にどうすればよいあ僕自身思いついてないので、今のところは「誰でも」は気にしなくてもよいかなって考えています。

**Comment by yasulab** [comment]
Cut out `誰でも`.

**Comment by hanachin** [comment]
> IDやPASSを公開せずに、READ ONLY で誰でも GTT から archive.zip をダウンロードできるとよさそうかなって考えていたんだけれど、ちょっと具体的にどうすればよいあ僕自身思いついてないので、今のところは「誰でも」は気にしなくてもよいかなって考えています。

GTTででドキュメント共有すれば誰でもダウンロード出来そうですね。

**Comment by yasulab** [comment]
@hanachin 

> GTTでドキュメント共有すれば

確かに共有すれば大丈夫なんだけど、そのためには

1. メールアドレスを教えてもらう
2. GTT上でから全てのドキュメントをチェックする
3. 教えてもらったメールアドレスに共有する

っていった作業が発生してしまうので、なるべくやりたくないのよね :sweat: あと、「誰にどこまで共有しているか? (漏れがあれば別途共有する)」って作業が結構頻繁にあって、今は人数が少ないからなんとかなっているけど、これが５人とか10にんとかになると困るなぁと考えています :sweat_drops:

**Comment by hanachin** [comment]
なるほど、1、2、3が自動化出来ても、新規追加されたドキュメントを共有したり、漏れのチェックするのは大変そうですね。
