### ISSUE TITLE
誰でもGTTから `archive.zip` をダウンロードできるようにしたい

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#184]
## 関連 Issue/PR
- #180 GTTから `archive.zip` をダウンロードできるスクリプトを作成する 
- #181 Add gtt-downloader gem Fix #180
## 背景

cf. [#180 コメント](https://github.com/yasslab/railsguides.jp/issues/180#issuecomment-110306965)

> > GTTでドキュメント共有すれば
> 
> 確かに共有すれば大丈夫なんだけど、そのためには
> 1. メールアドレスを教えてもらう
> 2. GTT上で全てのドキュメントをチェックする
> 3. 教えてもらったメールアドレスに共有する
> 
> っていった作業が毎回発生してしまうので、なるべくやりたくないのよね :sweat: あと、「誰にどこまで共有しているか? (漏れがあれば別途共有する)」って作業が結構頻繁にあって、今は人数が少ないからなんとかなっているけど、これが５人とか10人とかになると困るなぁって考えています :sweat_drops: 
> 
> また、共有すると書き込み権限を付与することになるので (なおPRみたいな便利機能はない)、誰にでも書き込み権限を与えて翻訳作業の妨げになるのは防ぎたいです。
## 問題

GTTのアクセス権を持っていない人が、最新版の `archive.zip` を入手できない
## 目的

誰でも最新版の `archive.zip` を入手できる
## 実装方法

うーん...今のところあまり良いアイデアがないです :sweat:

**Comment by hanachin** [comment]
現状だと次のように運用しているので、最新版のarchive.zipはGitHubから誰でもダウンロード出来ます。GTTからダウンロードしたファイルと変わりありません。

1. GTTの方で訳文や原文ファイルを修正する
2. 人間が最新版のarchive.zipをダウンロードし、このリポジトリに追加する

ただし、次のような場合はGTTからダウンロード出来るarchive.zipと、このリポジトリ内のarchive.zipに差が出てきます。

1. GTTの方で訳文や原文ファイルを修正する
2. 人間が最新版のarchive.zipをダウンロードし、このリポジトリに追加するのを忘れる

この場合GTTにアクセス権がない人が最新版のarchive.zipを入手出来ないのがこのissueだと認識しています。

**Comment by hanachin** [comment]
[yasslab/gtt-downloader](https://github.com/yasslab/gtt-downloader)の実装のためarchive.zipを何度かダウンロードして試していたのですが、ある程度の回数を超えると、ダウンロードできなくなることがありました。ダウンロード回数に制限があるかもしれません。

案1.
定期的に最新版のarchive.zipをダウンロードしてどこかに置くbotをつくる
置く場所はGitHubでもS3でもどこでもいい
botにやらせれば追加し忘れなどがない
GTTにアクセス権がない人でも、ある一定時間を置けばbotが最新版のarchive.zipをダウンロードしてくるので、最新版のarchive.zipを入手できる

案2.
メールアドレスを入れるだけでGTTでRailsGuidesのファイルを共有できるようにする
GTTへのアクセス権がなくて最新版がダウンロードできないのが問題なので、GTTのアクセス権を付与して、アクセス権を与える。

**Comment by hanachin** [comment]
[yasslab/gtt-downloader](https://github.com/yasslab/gtt-downloader)の実装のためarchive.zipを何度かダウンロードして試していたのですが、ある程度の回数を超えると、ダウンロードできなくなることがありました。ダウンロード回数に制限があるかもしれません。

**Comment by yasulab** [comment]
具体化あざす! description に追記しておきました :+1:

**Comment by hachi8833** [comment]
現在はGTT（Google Translator Toolkit）の運用は想定されていないと思われるので、こちらはcloseしてよいと思われます。@Yuppymam ご確認お願いします🙇
