### ISSUE TITLE
Rails アプリケーションを設定する内のサンプルコードの間違い

### ISSUE THREAD

**Issue by deg84** [yasslab/railsguides.jp#187]
http://railsguides.jp/configuring.html
```
$ rails runner 'puts ActiveRecord::Base.connections'
```

http://guides.rubyonrails.org/configuring.html
```
$ bin/rails runner 'puts ActiveRecord::Base.configurations'
```

configurationsがconnectionsになっているようです。

**Comment by yui-knk** [comment]
ご連絡ありがとうございます。

本家では　https://github.com/rails/rails/commit/17668f34c1c7441ea76577e2e7cca0f7f442222f　で修正されているようです。

**Comment by yasulab** [comment]
報告ありがとうございます!

こちら、後ほど修正しておきますね :+1: 

`ActiveRecord::Base.connections` -> `ActiveRecord::Base.configurations`
