### ISSUE TITLE
7.4 CSSインジェクション

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#196]
> CSSインジェクションの説明に最適なのは、かの有名な[MySpace Samyワーム](http://namb.la/popular/tech.html). This worm automatically sent a friend request to Samy (the attacker) simply by visiting his profile. 

と訳しもれがあるので、以下の訳をあてようかと思います。

> Samy(攻撃者)のプロフィールページを見るだけで、ワームは自動的にSamyへ友達申請を送ります。

**Comment by hachi8833** [comment]
修正しておきました。セグメントがくっついていたので分割が必要でした。後半はTMに訳がありました。
