### ISSUE TITLE
セキュリティガイドで固有名詞を訳しすぎているようです

### ISSUE THREAD

**Issue by moro** [yasslab/railsguides.jp#197]
セキュリティガイド2.8 の 

http://railsguides.jp/security.html#%E3%82%BB%E3%83%83%E3%82%B7%E3%83%A7%E3%83%B3%E5%9B%BA%E5%AE%9A%E6%94%BB%E6%92%83-%E5%AF%BE%E5%BF%9C%E7%AD%96

> ユーザー管理用に、有名なRESTful認証プラグインを導入しているのであれば、

は、`RestfulAuthentication` という名前のプラグイン(懐かしい...)のことかと思います。

とはいえ、プラグイン機構はすでにオワコンなので、本家のテクストから見直すとよいかもしれませんね。と、書くだけ書いておきます(すみません)

**Comment by yasulab** [comment]
おぉ、ご指摘ありがとうございます! 

原著の方も古くなっている可能性もあるので、そちらもチェックしておきます! :white_check_mark:

**Comment by yasulab** [comment]
原著の方のチェックはまだなので、そちらのチェックが終わったら閉じるようにします。

**Comment by hamadata** [comment]
http://guides.rubyonrails.org/security.html#session-fixation-countermeasures

If you use the popular Devise gem for user management, 

とあるので、原文のほうはアップデートされているようです。

**Comment by yasulab** [comment]
@hamadata ご指摘ありがとうございます! 😸 修正しました 🔧 💨
