### ISSUE TITLE
association_basics 4.3.4 オブジェクトが保存されるタイミング

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#198]
> If any of these saves fails due to validation errors, then the assignment statement returns false and the assignment itself is cancelled.

=>

> 関連付けられているオブジェクト同士の1つでも検証(validation)のために保存に失敗すると、アサインの状態からはfalseが返され、アサインはキャンセルされます。

ですが

> 関連付けられているオブジェクトの1つでも検証(validation)エラーで保存に失敗すると、アサインの式からはfalseが返され、アサインはキャンセルされます。

に修正したいです。

一番のポイントは assignment statement で、アサインの状態という訳は assignment status などへの読み間違いだと思います。

BTW  原文ですが、statement は expresion の方が適切でしょうか？

**Comment by hachi8833** [comment]
修正お願いします
