### ISSUE TITLE
「2 アセットパイプラインの使用方法」の訳について

### ISSUE THREAD

**Issue by rono23** [yasslab/railsguides.jp#199]
Rails 4.2 では、`serve_static_assets`はdeprecatedになり、`serve_static_files`にrenameされましたが、訳が古いままになっています。

> アセットは引き続きpublicディレクトリ以下に置くことも可能です。config.serve_static_assetsがtrueに設定されていると、publicディレクトリ以下に置かれているあらゆるアセットはアプリケーションまたはWebサーバーによって静的なファイルとして取り扱われます。プリプロセスが必要なファイルはapp/assetsディレクトリの下に置く必要があります。

http://railsguides.jp/asset_pipeline.html

> Assets can still be placed in the public hierarchy. Any assets under public will be served as static files by the application or web server when config.serve_static_files is set to true. You should use app/assets for files that must undergo some pre-processing before they are served.

http://guides.rubyonrails.org/asset_pipeline.html

**Comment by hachi8833** [comment]
ご指摘ありがとうございます。

安川さん、GTTで訳文だけ修正しました。ソース更新となるとちょっと手間なので。

**Comment by yui-knk** [comment]
@rono23  @hachi8833  ありがとうございます！

**Comment by yasulab** [comment]
@yui-knk 対応ありがとうございます! 昨日今日とPrivateがゴタゴタしていてだいぶ対応がおくれました :bow: :sweat_drops:
