### ISSUE TITLE
configuring

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#200]
> ENV["RAILS_CACHE_ID"]とENV["RAILS_APP_VERSION"]は、Railsのキャッシュを扱うコードで拡張キャッシュを生成するために使用されます。これにより、This allows you to have multiple separate caches from the same application.

と訳しもれがありました。

> これにより、同一のアプリケーションに対して複数の独立したキャッシュをもつことができます。

のような訳でどうでしょうか？

**Comment by hachi8833** [comment]
TMに訳があったので修正しました。

この手の訳漏れは、何かのはずみで作業中の訳が残ってしまったケースがほとんどなので、GTTでセグメントを開くとあっさり出てきたりします。

**Comment by hachi8833** [comment]
一度セグメントに入れれば固定されるはずなのですが、たまにこういうことが起きます。ICE (緑色) でも起きたりします。

**Comment by yui-knk** [comment]
ありがとうございました！
