### ISSUE TITLE
asset_pipeline 表記ブレ

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#201]
precompile arrayの訳に対して以下の二つがあたっているので統一したいです。
* プリコンパイルアレイ
* precompile配列

**Comment by hachi8833** [comment]
あー、これどっちにしましょうかね。

**Comment by yasulab** [comment]
アカデミアでは「プリプロセッサ」や「プリコンパイル」といった用語はよく使われていますが、「アレイ」は「配列」として使われることが多いので、

**プリコンパイル配列** で良いかなぁと考えておりますが、いかがでしょう?

**Comment by hachi8833** [comment]
それにしましょう。

**Comment by yasulab** [comment]
修正しておきます :+1:
