### ISSUE TITLE
docset で画像が表示されない

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#203]
おそらくは画像のパスが間違っているのかも...?

![screen shot 2015-08-16 at 17 28 44](https://cloud.githubusercontent.com/assets/155807/9292554/9ea986e2-443c-11e5-846c-37033a311295.png)

:thought_balloon: もし英語の方で docset がうまく動くようでしたら、 [rails/rails](https://github.com/rails/rails/tree/master/guides) の方にも PR を投げておくとよいかも :star2: 

cf. #202: Dash 用の Docset 作成タスクを追加しました。

**Comment by kminiatures** [comment]
https://github.com/yasslab/railsguides.jp/pull/205 で修正しました。

**Comment by yasulab** [comment]
mergeしました! お疲れ様です :bow:
