### ISSUE TITLE
active_record_migrations  3.8 changeメソッドを使用する

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#206]
> add_column
> ...
> drop_table (must supply a block)
> drop_join_table (must supply a block)

訳し漏れのようなので、

> blockを渡す必要がある
(箇条書きなので、である調にしています)
のように訳してはどうでしょうか

**Comment by hachi8833** [comment]
GTT で修正しました

**Comment by yasulab** [comment]
Deployed! :rocket:
