### ISSUE TITLE
getting_started (Ruby on RailsとRailsという表記について)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#207]
http://railsguides.jp/getting_started.html

で

> Ruby on Rails (以下Rails)

という表記が２回出てきています。またこの表記が出てくる以前にRailsと略している箇所もあります。

例：
> Railsアプリケーションの原型を素早く立ち上げる方法

https://github.com/rails/rails/blob/v4.2.1/guides/source/getting_started.md
など、原文は綺麗に書かれていて、Ruby on Railsという表現は(原則)一度しか出てきません。

ですので、
> このガイドでは、Ruby on Railsを初めて設定して実行するまでを解説します。

を
> このガイドでは、Ruby on Rails(以下Rails)を初めて設定して実行するまでを解説します。

に修正して、それ以降は原文にあわせて(原則)Railsという表記に修正してはどうでしょうか？

**Comment by hachi8833** [comment]
修正しました

**Comment by yasulab** [comment]
Deployed! :rocket:

**Comment by yasulab** [comment]
こちらの Issue、他の章でも同様のものがあるかもしれないですね。
見かけたらな修正しておきますね :wrench: :eyes:
