### ISSUE TITLE
getting_started (3.2 ブログアプリケーションを作成する)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#208]
> |vendor/|A place for all third-party code. In a typical Rails application this includes vendored gems.|

=>

> |vendor/|サードパーティによって書かれたコードはすべてここに置きます。通常のRailsアプリケーションであれば、商用のgemファイルもここに置かれます。|

商用のgemファイルという点が気になります。

> 外部提供されているgem

のようなニュアンスだと思います(そもそもなんでvendor/bundle というパスを使うことが多いのですかね)。

**Comment by hachi8833** [comment]
修正してみました。

**Comment by yasulab** [comment]
ありがとうございます! デプロイしておきました :rocket: 

> (そもそもなんでvendor/bundle というパスを使うことが多いのですかね)

細かくは検証してませんが、以前のRails (1.xとか2.x) で公式にそのパスが使われていたような気がします。なので、その名残りかな...とか :sweat_smile:
