### ISSUE TITLE
active_record_migrations (1 マイグレーションの概要)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#210]
> If you wish for a migration to do something that Active Record doesn't know how to reverse, you can use `reversible`:

=>

> Active Recordで対応できないマイグレーションを行いたい場合は、`reversible`を使用します。

ですが

> that Active Record doesn't know how to reverse

の箇所の訳が抜けています。
以下のような訳はどうでしょうか

> Active Recordが逆転する方法を知らないマイグレーションを行いたい場合は、`reversible`を使用します。

**Comment by yasulab** [comment]
@yui-knk 

> Active Recordが逆転する方法を知らないマイグレーション

うーん、もうちょっと良さそうな訳がありそうな気がしますが、後述の「 `reversible` を使用します」との対応関係を取ると、意訳せずにしっかりと訳したが良さそうですね...。

ちなみに、「逆転する方法をしらない」 == 「ロールバックできない」って意味かなと思うのですが、それであれば、例えば「Active Recordでロールバックできないマイグレーション」とかどうでしょう?

**Comment by yui-knk** [comment]
> Active Recordが逆転する方法を知らないマイグレーション

http://railsguides.jp/active_record_migrations.html#change%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B

> Active Recordがマイグレーションを逆方向に実行 (ロールバック) する方法を自動的に理解してくれるため、

と近い表現です。
ロールバックの方法を自動的に理解してくれているというニュアンスが重要だと思い、今のような訳を提案しました。

**Comment by yasulab** [comment]
「逆転」よりは「逆方向に実行」の表現の方が個人的にしっくりきます。

さらに、ニュアンスの件も踏まえて、

>  Active Recordがマイグレーションを逆方向に実行 (ロールバック) できない場合、`reversible` を使用します。

とかどうでしょう?

**Comment by yui-knk** [comment]
> Active Recordがマイグレーションを逆方向に実行 (ロールバック) する方法を推測できない場合、`reversible` を使用します。

ではどうですか？

**Comment by yasulab** [comment]
> Active Recordがマイグレーションを逆方向に実行 (ロールバック) する方法を推測できない場合、reversible を使用します。

おぉ! 「推測」いいですね! :star2: 

「を」が１文で２回使われている点は直したほうがいいと思うので、そこだけ修正して取り込んでみますね :+1:

**Comment by yasulab** [comment]
前後の文脈から主語が「Active Record」であることは自明なので、日本語っぽく主語を略してみます。

> マイグレーションを逆方向に実行 (ロールバック) する方法が推測できない場合、`reversible` を使用します。

**Comment by yui-knk** [comment]
@yasulab 確認しました。ありがとうございます！

**Comment by yasulab** [comment]
こちらこそ、ご指摘ありがとうございました〜 :+1:

**Comment by yasulab** [comment]
:thought_balloon: 余談ですが、先日 YAPC::Asia でチラ見せした継続的翻訳システムについてですが、開発がある程度終わったら、ちょっと触って頂けると嬉しいです :blue_book: (現在はまだOrganization機能がないのでチーム間で共有みたいなことができない感じです... :sob: )
cc/ @hanachin
