### ISSUE TITLE
active_record_migrations (3.11 以前のマイグレーションを逆転する)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#211]
コードのコメントで

> \# copy-pasted code from ExampleMigration

の箇所の訳が漏れているので、

> ExampleMigrationのコードをコピーアンドペースト

のような訳をあててはどうでしょうか

**Comment by yasulab** [comment]
指摘あざす!

読みやすさを考慮して、

> ExampleMigrationのコードをコピー＆ペースト

という形に少し修正して取り込もうと思います :+1:
