### ISSUE TITLE
Rails のルーティング routing.html ( 2.1 Web上のリソース ) typo修正案

### ISSUE THREAD

**Issue by scriptwork** [yasslab/railsguides.jp#214]
「 2.1 Web上のリソース 」 の最後の１行で

> Railsはこのリクエストをphotosコントローラ内のdestroy~~**コントローラ**~~に割り当て

は

> Railsはこのリクエストをphotosコントローラ内のdestroy**メソッド**に割り当て

でいかがでしょうか。

または
原文で the destroy method となっていますが、ひとつ前の段落で
「 特定のコントローラ内アクションにマッピング 」と書かれていますので
訳語の統一として destroy**アクション** でもいいと思います。

**Comment by yui-knk** [comment]
@scriptwork ありがとうございます。https://github.com/rails/rails/pull/22004　でactionに修正したので、"アクション"に合わせるようにしました:)
