### ISSUE TITLE
docrailsへのリンクを消す

### ISSUE THREAD

**Issue by hanachin** [yasslab/railsguides.jp#219]
日本語版にも https://github.com/rails/rails/commit/6cb1b6724c313c608cf4063fc22886faa19df9be と同様の修正を加えたほうがよさそう
http://railsguides.jp/contributing_to_ruby_on_rails.html

**Comment by yui-knk** [comment]
昼休みにやっておきます

**Comment by yui-knk** [comment]
@yasulab どちらも行の削除はしにくいので、訳注を補うのでいいでしょうか？

**Comment by yasulab** [comment]
@yui-knk お、良いと思います! :ok_woman:

**Comment by hanachin** [comment]
修正ありがとうございます :pray:

**Comment by yui-knk** [comment]
@yasulab そもそもforkもとをどうするのかとか、rails/docrailsのwikiの内容をrails/railsに以降ないととか。。。

**Comment by yui-knk** [comment]
後者はguideあたりに移行するのでよければ、PRを本家になげます！

**Comment by yui-knk** [comment]
@hanachin :+1:

**Comment by yasulab** [comment]
> そもそもforkもとをどうするのかとか、rails/docrailsのwikiの内容をrails/railsに以降ないととか。。。

日曜の大江戸Ruby会議には僕も参加するので、発表の後とか懇親会のときとかにちょっと相談させてください ;)

**Comment by yui-knk** [comment]
承知しました！
