### ISSUE TITLE
『Active Record クエリインターフェイス 14.1 引数を渡す』中の訳文改善提案

### ISSUE THREAD

**Issue by ymoto** [yasslab/railsguides.jp#220]
[Active Record クエリインターフェイス 14.1 引数を渡す](http://railsguides.jp/active_record_querying.html#%E5%BC%95%E6%95%B0%E3%82%92%E6%B8%A1%E3%81%99) の

> しかし、このスコープでできる機能は、クラスメソッドでできる機能と重複しています。

という訳文ですが、日本語として不自然（意味がよくわからない）に感じます。

原文は

> However, this is just duplicating the functionality that would be provided to you by a class method.

ですので、直訳すれば

> しかし、これ（スコープに引数を渡す機能）はクラスメソッドによって提供される機能を単に複製したものです。

のような意味かと思いますので、もう少し原文の意味が取りやすい訳文にしていただればと思いますが、いかがでしょうか。

**Comment by yasulab** [comment]
ご提案ありがとうございます :smile: 「必ず直訳する」という方針を採っているわけではないのですが、頂いた案の方が日本語として読みやすそうですね ;) 

> もう少し原文の意味が取りやすい訳文にしていただればと思います

量が多いのと、更新速度が非常に速いので、全ての文章を１つずつ十分に吟味することはできていません :sweat_drops: とりあえずの訳をdumpしておいて、今回のように指摘された箇所を順次改善していくスタイルでやっているので、引き続き気になる点があればご指摘して頂けたらと思います  :bow: (また、もし可能であればPRで出して頂けるともっと嬉しいです :blush: )
