### ISSUE TITLE
『Active Record クエリインターフェイス 14.3 スコープのマージ』中の訳文改善提案

### ISSUE THREAD

**Issue by ymoto** [yasslab/railsguides.jp#221]
[Active Record クエリインターフェイス 14.3 スコープのマージ](http://railsguides.jp/active_record_querying.html#%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%97%E3%81%AE%E3%83%9E%E3%83%BC%E3%82%B8) の

> where句と同様、AND条件を使用してスコープをマージできます。

という訳文ですが、原文は

> Just like where clauses scopes are merged using AND conditions.

ですので、直訳すれば

> where句と同様、スコープはAND条件を使用してマージされます。

のような意味かと思います。

「AND条件を使用してスコープをマージできます。」という訳は主語がなく読みづらいですし、「スコープはAND条件を使用してマージされます。」とも意味的にずれがありすぎるように感じるので、直訳調に修正することを提案します。

**Comment by yasulab** [comment]
> 「AND条件を使用してスコープをマージできます。」という訳は主語がなく読みづらいですし、「スコープはAND条件を使用してマージされます。」とも意味的にずれがありすぎるように感じるので、直訳調に修正することを提案します。

個人的にはそこまでの違和感を感じませんでした。また、このセクションで強調したいポイントは「スコープはmergeできる」という点なので、原案の方がシンプルかつ直接的にポイントを押さえているかなと思います :sweat:  ([原著](http://github.com/rails/rails)に対してPR (be -> can beみたいなPR) を送ってみた方が良いかもしれません... :sweat_drops: ) ( :thought_balloon: 後ろに続く文でもcanが使われているので、少なくとも「されます」よりは「できます」の方が適切そうです)

**Comment by yasulab** [comment]
あーでも、ちょっとコードも見てみましたが、「AND条件でmergeされる」という振る舞いを指摘しているので、その意味では「されます」の方が自然かもしれませんね...。こちらも少し考えてみます ><

ご指摘ありがとうございます!
