### ISSUE TITLE
『Active Record クエリインターフェイス 14.3 スコープのマージ』中の訳文改善提案（２）

### ISSUE THREAD

**Issue by ymoto** [yasslab/railsguides.jp#222]
[Active Record クエリインターフェイス 14.3 スコープのマージ](http://railsguides.jp/active_record_querying.html#%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%97%E3%81%AE%E3%83%9E%E3%83%BC%E3%82%B8) の

> ここでひとつ注意しなければならないのは、default_scopeをscopeやwhere条件よりも前に置いているという点です。

という訳文ですが、「default_scopeをscopeやwhere条件よりも前に置いている」という部分の意味がわかりづらいと感じます。

原文は

> One important caveat is that default_scope will be prepended in scope and where conditions.

ですので、

> ここでひとつ注意しなければならないのは、scopeやwhere条件では、default_scopeが前に追加されるという点です。

のような意味かと思います。

「前に置いている」とすると、コードを書く人が前に置いているようにも読み取れてしまいますが、この文では、結果として生成されるSQLにおいて、scopeやweher条件の前にdefault_scopeが追加されるということが要点かと思いますので、「default_scopeが前に追加される」ということが読み取れる訳文に修正することを提案します。

**Comment by yasulab** [comment]
> 「前に置いている」とすると、コードを書く人が前に置いているようにも読み取れてしまいます

こちら、確かにそうですね :sweat_drops: コードの置かれている位置ではなく、処理の順序が要点なので、「default_scopeの方が先に追加される / 優先される」といった訳に修正してみます ;) ( :thought_balloon: コード例で意図的にコードの位置を変えた方が分かりやすそうかも...?)

ご指摘ありがとうございました!
