### ISSUE TITLE
Railsエンジン入門（4.2 エンジンの設定）の誤字（基に->元に）

### ISSUE THREAD

**Issue by myokoym** [yasslab/railsguides.jp#227]
Railsエンジン入門（4.2 エンジンの設定）に誤字と思われる箇所があったのでご報告します。
http://railsguides.jp/engines.html#%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%B3%E3%81%AE%E8%A8%AD%E5%AE%9A

誤: blorghエンジンによるすべてのマイグレーションを基に戻したい場合は以下のようなコマンドを実行します。
正: blorghエンジンによるすべてのマイグレーションを元に戻したい場合は以下のようなコマンドを実行します。

**Comment by yasulab** [comment]
ご指摘ありがとうございます! 早速修正しておきました :+1:
