### ISSUE TITLE
contributing_to_ruby_on_rails (Active Recordをテストする) の訳について

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#238]
> This is how you run the Active Record test suite only for SQLite3:

を

> SQLite3 のみ、Active Recordのテストで以下を実行します。

と訳している箇所ですが、

"以下の手順で、SQLite3のみを対象にActive Recordのテストを実行します。"のような意味ですので、現在の訳では少し意味がずれています。
また、

> You can now run the tests as you did for `sqlite3`.

=>

> これで、`sqlite3`で行った場合と同様にテストを実行できるようになります。

の箇所も"`sqlite3`のときと同様に、以下の手順で各アダプターを対象にテストを実行することができます。"のほうが適切だと思います。

**Comment by yasulab** [comment]
おぉ、確かに。ご指摘ありがとうございます! こちらで修正しておきますね :wrench:

**Comment by yui-knk** [comment]
Thx :tada:
