### ISSUE TITLE
アセットパイプライン「アセットの編成」内の訳について

### ISSUE THREAD

**Issue by kazutomi** [yasslab/railsguides.jp#239]
「パスの検索」の項の最後に

> ここでご注意いただきたいのは、参照したいファイルがマニフェストの外にある場合はそれらをプリコンパイル配列に追加しなければならないこと、さらにこれらはproduction環境では利用できないという点です。

とあり、原文は

> It is important to note that files you want to reference outside a manifest must be added to the precompile array or they will not be available in the production environment.

かと思いますが、この「or」は「さもなくば」の意味で、訳は「……プリコンパイル配列に追加されねばならない、そうしなければproduction環境では利用できない」のようになるものと思います。

**Comment by yasulab** [comment]
こちらもご指摘ありがとうございます!

次のような感じで修正してみました :smile_cat: 

> ここでご注意いただきたいのは、参照したいファイルがマニフェストの外にある場合は、それらをプリコンパイル配列に追加しなければならないという点です。追加しない場合、production環境で利用することができなくなります。

他にも何か気になる点がありましたらお気軽にご連絡ください :star2:
