### ISSUE TITLE
カラム修飾子を判別しやすくする

### ISSUE THREAD

**Issue by k-utsumi** [yasslab/railsguides.jp#240]
「Active Record マイグレーション」内の「3.5 カラム修飾子」にある修飾子のリストについて、区切りが分かりづらいと感じました。
http://railsguides.jp/active_record_migrations.html#%E3%82%AB%E3%83%A9%E3%83%A0%E4%BF%AE%E9%A3%BE%E5%AD%90

下記の項のようにハイフンで分割するのはいかがでしょう。
http://railsguides.jp/active_record_validations.html#length

**Comment by yasulab** [comment]
ご指摘ありがとうございます! こんな感じで修正してみました :wrench: 

<img width="574" alt="screen shot 2016-03-29 at 23 15 48" src="https://cloud.githubusercontent.com/assets/155807/14111138/82b5705c-f604-11e5-999d-c7d1d1a011a2.png">

**Comment by k-utsumi** [comment]
迅速なご対応ありがとうございます。
判別しやすくなったように思います。
