### ISSUE TITLE
Railsガイド内で検索が出来たら嬉しいです

### ISSUE THREAD

**Issue by takiy33** [yasslab/railsguides.jp#241]
いつも便利に読ませて頂いています。
WebページのRailsガイド内で検索が出来たら嬉しいと思いました。

**Comment by yasulab** [comment]
電子書籍 (Epub/PDF) や同梱のdocsetで全文検索/逐語検索が可能なので、よければこちらのご購入をご検討していただけると幸いです...!! :star2: 

![Sample GIF](http://g.recordit.co/l8Wyl9OrGa.gif)

電子書籍: http://railsguides.jp/options.html

**Comment by takiy33** [comment]
ご丁寧な回答ありがとうございます。
電子書籍版を購入させて頂きます。

**Comment by yasulab** [comment]
いえいえ、他にも何か気になる点があればお気軽にご連絡ください! :smile_cat:
