### ISSUE TITLE
Active Record コールバック「コールバックの停止」

### ISSUE THREAD

**Issue by kazutomi** [yasslab/railsguides.jp#242]
現在の警告の訳：

> ActiveRecord::Rollbackを除いて、コールバック連鎖後にRailsによって再発生したあらゆる例外は停止します。ActiveRecord::Rollback以外の例外が発生すると、saveやupdate_attributesなどのようにメソッドが例外を発生することを想定していないコード(通常trueまたはfalseのいずれかを返します)は中断します。

原文：

> Any exception that is not ActiveRecord::Rollback will be re-raised by Rails after the callback chain is halted. Raising an exception other than ActiveRecord::Rollback may break code that does not expect methods like save and update_attributes (which normally try to return true or false) to raise an exception.

ここはむしろおよそ

> `ActiveRecord::Rollback`以外の例外は、コールバックチェインがその例外によって停止した後に、Railsによって再び発生させられる。このためコールバックチェイン内で`ActiveRecord::Rollback`以外の例外を起こすと、`save`や`update_attributes`（これらは通常trueかfalseを返そうとする）などのメソッドが例外を起こすことを想定していないコードを壊す恐れがある。

という意味だと思います。つまり、`ActiveRecord::Rollback`以外の例外をRailsはわざと再発生させてアプリケーションに伝える（一回目は自分で捕まえてデータベースをロールバックする）、だから if obj.save 〜 みたいな処理しかしてないコードがあると、そういう例外を上げるコールバックを書くとうまく動かなくなるかもよ、ってことじゃないでしょうか。

**Comment by yasulab** [comment]
ご指摘ありがとうございます! こんな感じで修正してみました 🔧 

> WARNING: `ActiveRecord::Rollback`以外のあらゆる例外は、コールバック連鎖がその例外によって停止した後に、Railsによって再び発生させられます。このため、コールバック連鎖の中で`ActiveRecord::Rollback`以外の例外が起こると、メソッドが例外を発生することを想定していないコード (通常時にtrueかfalseを返そうとする`save`や`update_attributes`メソッドなど) が壊れる恐れがあります。

**Comment by kazutomi** [comment]
括弧内外の語句の位置が原文とかなり離れた感がありますので、例えば

> ［…］以外の例外が起こると、`save`や`update_attributes`などの（通常はtrueやfalseを返そうとする）メソッドは例外を発生しないと想定しているコードが壊れる恐れがあります。

みたいな感じでいかがでしょうか？

**Comment by yasulab** [comment]
直訳は読みづらいので、基本的に直訳は避けています (原文の完全な翻訳よりも読みやすさを重視しています) 💦  

とはいえ、もう少し読みやすくできるとは思うので、頂いたフィードバックを元に、日本語として読みやすくして修正してみました 🔧 

> このため、コールバック連鎖の中で`ActiveRecord::Rollback`以外の例外が起こると、 `save`や`update_attributes`などの通常はtrueやfalseを返そうとするメソッド (例外は発生しないと想定しているコード) が壊れる恐れがあります。

**Comment by kazutomi** [comment]
なるほど、原文から離れてよいという方針なのですね。なら "break" を無理に一語で「壊れる」と訳す必要はないですね。

えと、ひとつ意味的に気になってるのは、 8fe47e8 も 54c8cec もそうなのですが、「壊れる」のが（ActiveRecordが提供している）`save`や`update_attributes`というメソッド自体だと読めるところです。私の理解では、原文の意味するのは、「壊れる」のは、`save`や`update_attributes`を使っている（アプリケーションの）コードだと思います。

例えばこういうシチュエーションを想定しているのではないかと：

1. `if obj.save ...` みたいなコードをプログラマが書く。（失敗なら false が返るはずと思って）
2. そのモデルにコールバックを書こうとする
3. プログラマが何らかの理由で_before_コールバック内で例外を起こしたくなるとか、_after_コールバックで（ロールバックするために必要だから）例外を起こしたくなる
4. そのときに`ActiveRecord::Rollback`以外の例外を使ってそういうコールバックを書くと、1.で書いたコードは例外に対処してないからうまく動かなくなる＝「壊れる」（broken なコードになる）

もしそうなら、警告の気持ちとしては「コールバック内で例外を起こすことでロールバックさせるときには気をつけなさい」ってことだと思うので、この気持ちを入れつつ私の前の試訳をもう少し読みやすく意訳的にするなら、

> `ActiveRecord::Rollback`以外の例外は、その例外によってコールバック連鎖が停止した後でRailsによって再度発生させられます。このため、`ActiveRecord::Rollback`以外の例外をコールバック内で起こすと、`save`や`update_attributes`などのような（通常はtrueかfalseを返そうとする）メソッドが例外を起こさないと想定しているコードがうまく動かなくなる恐れがあります。

くらいでしょうか……

あと、ついでに見つけたのですが、この警告の直前の訳文

> _after_コールバックの場合は例外を発生することによってのみ、コールバックの連鎖を停止することができます。

原文

> _after_ callbacks can only accomplish that by raising an exception.

ですけど、"that" はコールバックチェインの停止だけでなくROLLBACKの発行も指しているので、直訳的には

> _after_コールバックの場合は例外を発生することによってのみ、コールバック連鎖の停止およびROLLBACKの発行をさせることができます。

より意訳すれば

> _after_コールバックの場合は例外を発生することによってのみ、コールバック連鎖の停止とトランザクションのロールバックをさせることができます。

みたいな方が、「コールバックチェインは止まると書いてあるが、ロールバックはするのか？」という疑問が出なくてよさそうに思います。

**Comment by yasulab** [comment]
> うまく動かなくなる恐れがあります。

確かに「壊れる」より、こちらの訳の方が読みやすいですね! 🌟 

> メソッドが例外を起こさないと想定しているコードが

こちらは助詞の「が」が連続していて読みづらいので、カッコを使ってもう少し読みやすくしてみますね 🔧 

> 「コールバックチェインは止まると書いてあるが、ロールバックはするのか？」という疑問が出なくてよさそうに思います。

ありがとうございます! こちらも頂いた案で修正しておきますね 👌
