### ISSUE TITLE
「Rails の初期化プロセス」の「1.2 railties/lib/rails/app_rails_loader.rb」本文について

### ISSUE THREAD

**Issue by takiy33** [yasslab/railsguides.jp#252]
> exec_app_railsの主要な目的な、Railsアプリケーションにあるbin/railsを実行することです。

上記の文についてですが、「主要な目的な」より「主要な目的は」にした方が読みやすいと思いました。(個人的な感想です)
いかがでしょうか ❓ 

cf. [1.2 railties/lib/rails/app_rails_loader.rb](http://railsguides.jp/initialization.html#railties-lib-rails-app-rails-loader-rb)

**Comment by yasulab** [comment]
ご指摘ありがとうございます 😸 こちら誤字ですね 💦 修正します! 🔧
