### ISSUE TITLE
「Rails アプリケーションを設定する」の「3.6 Active Recordを設定する。」について

### ISSUE THREAD

**Issue by takiy33** [yasslab/railsguides.jp#253]
見出しの`3.6 Active Recordを設定する。`に「。」が付いていることに気が付きました。
他のタイトルに合わせて、「。」を削除するのが良いのでは、と思っています。

cf. [3.6 Active Recordを設定する。](http://railsguides.jp/configuring.html#active-record%E3%82%92%E8%A8%AD%E5%AE%9A%E3%81%99%E3%82%8B%E3%80%82)

**Comment by yasulab** [comment]
ご指摘ありがとうございます! こちら修正しておきました 🔧 😸 ✨
