### ISSUE TITLE
脱字, 気になる和訳

### ISSUE THREAD

**Issue by pythonissam** [yasslab/railsguides.jp#254]
先ほどツイッターでぐちぐち言ってた者です。

[レイアウトとレンダリング] (http://railsguides.jp/layouts_and_rendering.html)
### [2.3.2] (http://railsguides.jp/layouts_and_rendering.html#renderとredirect-toの違い)

ここです。

> 上のフォームのコードでは、@bookインスタンス変数がnil場合に問題が生じる可能性があります。

細かいですが、「 nil の場合」の「の」が抜けています。
そしてその下の、

> render :actionは対象となるアクションのコードを実行しないことを思い出してください。

という部分なんですが、今までの説明から、**render がブラウザにレスポンスを返す**ために使われることは理解できました。しかしそこから、**render :actionは対象となるアクションのコードを実行しない**ということが論理的に言えるのかどうか、というのが僕の疑問です。なので僕は Remember を、**忘れないでね、覚えといてね**的な訳にしました。

また原文が**思い出せよ!**という意味だったとしても、単に、**render はブラウザにレスポンスを返すだけです**、とでも書いてもらった方がわかりやすかったような気がします。なぜなら、**そもそも index ってアクションに行かねぇよ**というニュアンスが出るからです。

**Comment by yasulab** [comment]
ご指摘ありがとうございます! 修正しておきました 🔧 😸

**Comment by pythonissam** [comment]
お疲れさまです。ありがとうございました！
