### ISSUE TITLE
「Active Record クエリインターフェイス」の「1.1.4 last」本文について

### ISSUE THREAD

**Issue by takiy33** [yasslab/railsguides.jp#257]
> lastメソッドは、モデルにレコードが1つもない場合にnil`を返します。

上記の文ですが、「nil`」になっています。

cf. http://railsguides.jp/active_record_querying.html#last

**Comment by yasulab** [comment]
ご報告ありがとうございます! 修正しておきました 🔧 😸

**Comment by takiy33** [comment]
ありがとうございます 😋
