### ISSUE TITLE
アップグレードガイドのマークダウンエラー

### ISSUE THREAD

**Issue by hachi8833** [yasslab/railsguides.jp#258]
https://goo.gl/YPJsVd

>:infoを指定すると現在のデフォルト設定が使用され、
>:debugを指定すると今後のデフォルト設定が使用される

の直前のコード開始マークダウン`ruby`と、その前の行との間に空行がないためにマークダウンが無効になっています。

**Comment by yasulab** [comment]
ご指摘ありがとうございます 😸 修正しました! 🔧
