### ISSUE TITLE
Rails 5のリリースノートのリンク先URLのスキーマがhttpshttpsになっている

### ISSUE THREAD

**Issue by hanachin** [yasslab/railsguides.jp#259]
```
> *  `Date`、`Time`、`DateTime`の`#yesterday`と`#tomorrow`に、`#prev_day`と`#next_day`に対応するメソッドを追加。
>    ([Pull Request](httpshttps://github.com/rails/rails/pull/18335))
```
https://github.com/yasslab/railsguides.jp/blob/japanese/guides/source/ja/5_0_release_notes.md

**Comment by yasulab** [comment]
原著の間違いだったのでPR出しておきます 💨

**Comment by yasulab** [comment]
Fixed Japanese RailsGuides🔧 ✨ And sent feedback to original repo 😸 
https://github.com/rails/rails/pull/26186
