### ISSUE TITLE
SinatoraがShinatoraと表記されている

### ISSUE THREAD

**Issue by siman-man** [yasslab/railsguides.jp#260]
「Rails による API 専用アプリ」の「2 JSON APIにRailsを使う理由」の文中に

> 「RailsでJSONを出力するのは大げさすぎませんか？Shinatraじゃだめなんですか？」

とありますが、「Shinatora」ではなく「Sinatora」だと思われます。

**Comment by yasulab** [comment]
> Sinatora

Sinatra ですかね ;) 報告あざす!

**Comment by siman-man** [comment]
あっすみません「Sinatra」でした :sweat_drops:

**Comment by yasulab** [comment]
修正しました! 🔧 😸
