### ISSUE TITLE
bin/rails routes 

### ISSUE THREAD

**Issue by keiisato** [yasslab/railsguides.jp#269]
Rails を始めたばかりのものです。
Rails をはじめよう　を試していますが下記のコマンドは正しいのでしょうか。
help とか確認しても見当たりません。またエラーもでます。
翻訳元が間違っているのかもしれませんが、可能なら正しく動作するものを記載してほしいです。

```
bin/rails routes
```

正しくは下記だと思っているのですが。

```
rake routes
````

下記も同様です。

```
$ bin/rails db:migrate
```

**Comment by yasulab** [comment]
> 翻訳元が間違っているのかもしれませんが、可能なら正しく動作するものを記載してほしいです。

@keiisato Rails 5.0 でやってますかね? 😅 💦 
Rails 4.2以下のバージョンで動かしていませんか?

**Comment by keiisato** [comment]
ご回答ありがとうございます。
rails 4.2.1 でやっていました。
Rails をはじめよう　の Rails のバージョンを確認するところで

```
"Rails 4.2.1"のように表示されれば、次に進むことができます。
```

となっていたので、4.2.1 でやっていたのですが、あとの手順は 5 が想定されているのですね。
rails 5 でコマンドがあるのは確認できましたので、間違いではないことはわかりました。

お手間じゃなければ Rails をはじめようの本文に一言補足していただければ助かります。

**Comment by yasulab** [comment]
> "Rails 4.2.1"のように表示されれば、次に進むことができます。

おぉ、そうだったんですね 😓 こちら修正しておきますね 🔧 💦

**Comment by yasulab** [comment]
@keiisato 修正しておきました! ご報告ありがとうございます 😸
