### ISSUE TITLE
コードの誤り：Active Record の関連付け (アソシエーション)

### ISSUE THREAD

**Issue by akirakoyasu** [yasslab/railsguides.jp#273]
http://railsguides.jp/association_basics.html#has-manyのオプション

に記載の下記コードについて
```
class Customer < ActiveRecord::Base
  has_many :orders, dependent: :delete_all, validate: :false
end
```

`validate:` には真偽値を渡しますので `:false`ではなく`false`が正しいと思います。

原著では `false` となっておりました。
http://guides.rubyonrails.org/association_basics.html#options-for-has-many

**Comment by yasulab** [comment]
ご指摘ありがとうございます! 😸 ✨  早速修正しておきますね🔧 💨

**Comment by wizpra-koyasu** [comment]
ありがとうございました！
