### ISSUE TITLE
誤表記

### ISSUE THREAD

**Issue by blp1526** [yasslab/railsguides.jp#274]
https://github.com/yasslab/railsguides.jp/blob/ff2daa38b1c522b1580d9cd8a592064b41866609/guides/output/ja/asset_pipeline.html#L842

> このオプションは次のような場合に便利です。アセットパイプラインを使用しない既存のプロジェクトがあり、そのプロジェクトの既存のパスを指定したり、別途新しいリソース用のパスを指定したりする場合なのです。

「なのです」となっています。

**Comment by yasulab** [comment]
@blp1526 ご指摘ありがとうございます 😸 修正しておきました! 🔧 💨
