### ISSUE TITLE
[訳文追加漏れ]ActionView概要中のjbuilderの説明

### ISSUE THREAD

**Issue by south37** [yasslab/railsguides.jp#275]
本体の RAILS GUIDES を読んでいると、「Action View Overview」の「Templates, Partials and Layouts」の章に 「3.1.3 Jbuilder」として jbuilder の説明を載せていました。
cf. http://guides.rubyonrails.org/action_view_overview.html#jbuilder
cf. https://github.com/rails/rails/blob/5-0-stable/guides/source/action_view_overview.md#jbuilder

一方、日本語訳版では「jbuilderの説明」は載せていないようでした。
cf. http://railsguides.jp/action_view_overview.html#%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%E3%82%92%E3%82%AD%E3%83%A3%E3%83%83%E3%82%B7%E3%83%A5%E3%81%99%E3%82%8B

訳文追加漏れに見えましたので、ご報告です！ 🙇 

### 本体の3.1.3
<img width="950" alt="action_view_overview_ _ruby_on_rails_guides" src="https://cloud.githubusercontent.com/assets/2713881/20645788/a24eedf6-b4ab-11e6-9445-b6303925e67f.png">

### 日本語訳版の3.1.3
<img width="775" alt="action_view_ ___rails_" src="https://cloud.githubusercontent.com/assets/2713881/20645826/6663aed8-b4ad-11e6-903c-c11e4a69b211.png">

**Comment by yasulab** [comment]
ご指摘ありがとうございます! 😸  こちら、Railsガイドがまだ Google Translator Toolkit (GTT) に依存している箇所なので、すぐには対応できなさそうです >< 💦 (GTTだと原著の更新に追いつくのが困難なんですよね 😓  )

Railsチュートリアルと同様に、Railsガイドも完全に[継続的翻訳システム](https://speakerdeck.com/yasulab/how-we-continuously-translate-tech-docs)に載せ替え終わればすぐに対応・修正できるようになるので、それまでは対応をお待ちいただけると助かります 🙏 💦 

システムを載せ換え後、原著の微細な更新に対応できるようになったら、こちらの Issue に取り掛かりますね! 🔧 💨 

cc/ @hachi8833 @hanachin

**Comment by south37** [comment]
分かりました、ありがとうございます！ 😄 
よろしくお願いします！ 🙇

**Comment by hachi8833** [comment]
本件修正済みにつきcloseします。

https://railsguides.jp/action_view_overview.html#jbuilder
