### ISSUE TITLE
chainの表記ゆれ

### ISSUE THREAD

**Issue by RyoYamamotoJP** [yasslab/railsguides.jp#279]
`chain` が `チェイン` と翻訳されていたり `チェーン` と翻訳されていたり、表記ゆれが気になりました。

**Comment by yasulab** [comment]
報告ありがとうございます! 😸  修正しておきました 🔧 💨

**Comment by RyoYamamotoJP** [comment]
ご対応ありがとうございますー。また何か見つけたら報告しますー。

**Comment by yasulab** [comment]
はい、何かあればお気軽にご連絡ください ;)
