### ISSUE TITLE
翻訳誤り? [アセットパイプライン] [2 アセットパイプラインの使用方法]

### ISSUE THREAD

**Issue by yasuoy** [yasslab/railsguides.jp#281]
いつも活用させていただいています。本当にありがとうございます。

さて、掲題序文の最終パラグラフ1文目について、

原文：In production, Rails precompiles these files to public/assets by default.

ですが、

「Railsは、productionモードではデフォルトでpublic/assetsファイル**を**プリコンパイルします。」

ではなく、

（それらapp/assetsのプリプロセスが必要なファイルを）
「Railsは、productionモードではデフォルトでpublic/assetsファイル**に**プリコンパイルします。」

ではないでしょうか？

**Comment by riseshia** [comment]
ご指摘ありがとうございます！！
@yasulab 問題ないようでしたらマージしてください！！😁

**Comment by yasulab** [comment]
修正しました! ご指摘ありがとうございました〜😸
