### ISSUE TITLE
カタカナ用語の末尾の長音表記

### ISSUE THREAD

**Issue by RyoYamamotoJP** [yasslab/railsguides.jp#284]
[Action Cable の概要](https://railsguides.jp/action_cable_overview.html) を読んでいて、"consumer" が "コンシューマー" と "コンシューマ" の２通りに翻訳されていました。 

同ページ内では "コンシューマー" と翻訳されている方が多いですが、他の用語（例：パブリッシャ、サブスクライバなど）と表記をそろえるのであれば"コンシューマ"で統一したほうがいいかもしれない...と思ったのですが、他にも"サーバー"や"ユーザー"などの表記もあるので、逆に"パブリッシャ"や"サブスクライバ"の方を長音ありに修正したほうがいい気がしてきました。

どちらに統一すればいいか判断できなかったので、Issueとして登録しますー。

**Comment by yasulab** [comment]
一部の例外を除けば、基本的に長音が良さそうです。

たしか「ユーザ」などが学術界で流行ったのは Microsoft がそういった翻訳の規範を作ったから、と伺いましたが、その Microsoft が「ユーザー」と長音する方針に規範を変更されたので、現在は長音を使わない理由はあまりなさそうです ;)

cf. [「コンパイラ」「プログラマ」などは従来通り - MSが長音付けルール変更、「ドライバ」を「ドライバー」に](http://www.atmarkit.co.jp/news/200807/25/microsoft.html)

**Comment by yasulab** [comment]
こちら、「サブスクリプション」という名詞を除き、それ以外のすべての変化系 (サブスクライブ、サブスクライバーなど) を全体的に修正しました 📝 💨
