### ISSUE TITLE
メンテナンスポリシーが5.0に対応していない

### ISSUE THREAD

**Issue by Peranikov** [yasslab/railsguides.jp#287]
原著の方はBug Fixes, Security Issues, Severe Security IssuesのCurrently included seriesが `5.0.Z, 4.2.Z.` になっているのに対し、日本語訳版は `4.2.Z、4.1.Z` (一部3.2.Zあり) のようです。

原著
http://guides.rubyonrails.org/maintenance_policy.html

日本語訳
https://railsguides.jp/maintenance_policy.html

**Comment by yasulab** [comment]
報告ありがとうございます :) 技術的な理由で更新が遅れていますが、こちらについては量もそこまで多くなさそうなので、後ほどパッチで対応できないか検討しておきますね 🤔

**Comment by Peranikov** [comment]
よろしくお願いします 🎉

**Comment by yasulab** [comment]
さっと直せたので対応しておきました! 😸 🔧 💨

**Comment by Peranikov** [comment]
ありがとうございます!
