### ISSUE TITLE
ほんの十数行ですが、「Action View の概要」の「5. ビューのパス」を和訳しましたので、そのお知らせです。

### ISSUE THREAD

**Issue by jun68ykt** [yasslab/railsguides.jp#292]
こんにちは。
Railsガイドを拝読しております。（電子書籍版も購入させて頂きました。）

ほんの十数行ですが、[5 ビューのパス](https://railsguides.jp/action_view_overview.html#%E3%83%93%E3%83%A5%E3%83%BC%E3%81%AE%E3%83%91%E3%82%B9) を、[原文の該当箇所](http://guides.rubyonrails.org/action_view_overview.html#view-paths)から和訳して、Qiitaに載せました。

[View Paths 和訳（Railsガイド）](http://qiita.com/jun68ykt/items/6280f5da054516bc8933)

拙い和訳ですが、もし使えそうであれば上記からご転載頂いてもかまいません。
以上です。

**Comment by yasulab** [comment]
ご連絡ありがとうございます😆 原文を更新する際にまとめて対応しようと思うので、こちらに追加しておきますね。
https://github.com/yasslab/railsguides.jp/issues/266

**Comment by hachi8833** [comment]
遅くなりましたが、本件更新済みにつきcloseします。
@jun68ykt ありがとうございました！🙇

https://railsguides.jp/action_view_overview.html#%E3%83%93%E3%83%A5%E3%83%BC%E3%81%AE%E3%83%91%E3%82%B9
