### ISSUE TITLE
サンプルコードの移植ミス？

### ISSUE THREAD

**Issue by junichirojp** [yasslab/railsguides.jp#293]
以下の段落内、サンプルコードの移植にミスがあったかと思いますので連絡します。
原文はGuestsCleanupJobだけど和訳文はMyJobになってます。
僕はRails初心者なので、MyJobというものに渡して使うのかと勘違いしてました。

https://railsguides.jp/active_job_basics.html#ジョブをキューに登録する
http://guides.rubyonrails.org/active_job_basics.html

**Comment by riseshia** [comment]
本家の方でいいです。翻訳の後で上になる例題と合わせて更新してされてますね。。。

@yasulab ソースコードとはいえ、原文が完全に変わっていますが、 直しておきましょうか？

**Comment by yasulab** [comment]
> 直しておきましょうか？

@riseshia ですね 💦 直しておいてもらえると助かります! 🙏

**Comment by junichirojp** [comment]
早速の対応ありがとうございます。
