### ISSUE TITLE
bin/merge-upstream で rails/rails の master ブランチをマージしたい

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#314]
@siman-man 先ほど久しぶりに動かしたらうまく動かなかったので、こちらの原因を調査して欲しいです 🙏 
master ブランチの `guides/` 以下の情報 (最新のRailsGuides) が欲しいので、次の部分だけ僕の方いじっています 🔧 

cf. https://github.com/yasslab/railsguides.jp/commit/5e7be9083d8234fd3e8f163c167f738c00cc6e29

**Comment by siman-man** [comment]
`origin/4-2-stable-20160420022536` ブランチのコミット情報がローカルに存在していなかったため、エラーが起きていたようです。現在はこのブランチが push されたので、`git fetch` でブランチ情報を更新してもらえれば、動くと思います。

自分も手元で動かしてみましたが大丈夫そうでした。（大量にコンフリクトは発生しましたが。。。

```
Auto-merging guides/assets/javascripts/guides.js
CONFLICT (content): Merge conflict in guides/assets/javascripts/guides.js
Auto-merging guides/Rakefile
CONFLICT (content): Merge conflict in guides/Rakefile
Automatic merge failed; fix conflicts and then commit the result.
+ echo 'merge https://github.com/rails/rails.git master(526fa1e63df7bf7d4229560c963a0d4f8248b218) failed.'
merge https://github.com/rails/rails.git master(526fa1e63df7bf7d4229560c963a0d4f8248b218) failed.
+ echo merge failed
merge failed
+ exit 1
```

**Comment by yasulab** [comment]
cf. https://github.com/yasslab/railsguides.jp/pull/317

**Comment by siman-man** [comment]
こちら #329 で取り込まれましたのでクローズしたいと思います。

**Comment by yasulab** [comment]
対応ありがとうございました〜 😸 👍
