### ISSUE TITLE
Ignore newlines in a sentence

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#315]
Let's consider how we can implement this kind of system for better translation:

> I think it would be better to teach the Translation Memory system to ignore word-wrapping that markdown doesn't care about -- or apply an automatic re-wrap in the pipeline before the translation system sees the source content.

cf. https://github.com/rails/rails/pull/28942#issuecomment-298289152

**Comment by yasulab** [comment]
RailsGuides のチームから意見をもらって、結果としては、こちら側で改行を無視する機能を実装する方向で進める形になりました。GTTだと実装できないけど、もとよりGitlateに移行する予定だったので、その機能をGitlate側に持たせる方向で実装しましょう 🔧💨

**Comment by yasulab** [comment]
## 実装案

- RailsGuides が使っている Markdown Parser と同じ Parser を実装or再利用して文章を整形すれば良さそう
- RailsGuides の [Parser](https://github.com/yasslab/railsguides.jp/blob/japanese/guides/rails_guides.rb) が認識できない改行は RailsGuides にも影響が出るので、そこはPRなどで修正する
- RailsGuides が無視できている改行は同じ Parser で無視すれば良い、という実装になりそう

cf. https://github.com/yasslab/railsguides.jp/tree/japanese/guides

**Comment by yasulab** [comment]
```
<div class="info"><p>Ruby 1.8.7 p248 and p249 have marshaling bugs that crash Rails. Ruby Enterprise Edition has these fixed since the release of 1.8.7-2010.02. On the 1.9 front, Ruby 1.9.1 is not usable because it outright segfaults, so if you want to use 1.9.x, jump straight to 1.9.3 for smooth sailing.</p></div><h4 id="the-update-task"><a class="anchorlink" href="#the-update-task">1.4 The Update Task</a></h4><p>Rails provides the <code>app:update</code> task (<code>rake rails:update</code> on 4.2 and earlier). After updating the Rails version
in the Gemfile, run this task.
This will help you with the creation of new files and changes of old files in an
interactive session.</p><div class="code_container">
```

> `<p>` タグで囲まれている文章中の改行は反映されてないので、見た感じが改行が消えたようになる

**Comment by yasulab** [comment]
HTMLだから見た目に出ていないだけで、HTMLの内部では改行されているので、文中から改行だけを取り除くやり方を別途調査する必要がある (少なくともmd->mdでは解決しない)

**Comment by hanachin** [comment]
HTMLの場合は連続した空白を単一の空白として扱う仕様があります

**Comment by hanachin** [comment]
https://www.w3.org/TR/html5/single-page.html#common-parser-idioms

**Comment by yasulab** [comment]
MarkdownをParseしてできたオブジェクトでは改行が消えてるのかなぁと思ったけど、そんなことはなかった... orz

**Comment by yasulab** [comment]
This issue can be solved by [yasslab/markdown_formatter](https://github.com/yasslab/markdown_formatter) (cf. #395 ), so I'll close this issue.

Thanks @siman-man for his big effort! 🎉 ✨
