### ISSUE TITLE
autoload_pathのコード誤表記

### ISSUE THREAD

**Issue by maskyo** [yasslab/railsguides.jp#316]
https://railsguides.jp/autoloading_and_reloading_constants.html#autoload-paths

```
config.autoload_paths += "#{Rails.root}/lib"
```

は原著だと

http://guides.rubyonrails.org/autoloading_and_reloading_constants.html

```
config.autoload_paths << "#{Rails.root}/lib"
```

となっており原著が正しいかと思いましたので報告させていただきます。

**Comment by yasulab** [comment]
ご指摘ありがとうございます! 😸 こちら修正しておきました 🔧 💨 
他にも何か気になる点があればお気軽にご連絡ください 📨 ✨
