### ISSUE TITLE
誤字がありました

### ISSUE THREAD

**Issue by knt45** [yasslab/railsguides.jp#321]
細かいですが。

https://railsguides.jp/action_controller_overview.html

14.1 デフォルトの500・404テンプレート

誤
ただし、これらはあくまで静的なHTMLファイルなので、RHTMLやERBは使用でいません。

正
ただし、これらはあくまで静的なHTMLファイルなので、RHTMLやERBは使用できません。

**Comment by riseshia** [comment]
報告ありがとうございます！
パッチPR作りましたので確認お願いしますー　@yasulab

**Comment by yasulab** [comment]
対応ありがとうございます! PR確認およびマージしました ;)
