### ISSUE TITLE
ブラウザの横幅が小さい状態だとコードブロックの表示がおかしくなる [PC]

### ISSUE THREAD

**Issue by siman-man** [yasslab/railsguides.jp#326]
PCで閲覧している際に、横幅が小さい状態だとコードブロックの表示がおかしくなります。(コードブロックの真ん中あたりの灰色部分が横に飛び出す）

フルサイズで表示

<img width="840" alt="full_width" src="https://cloud.githubusercontent.com/assets/1725620/26186123/38b2ecd4-3bca-11e7-8c1b-4cecad590c44.png">

画面の半分のサイズで表示

<img width="841" alt="half_width" src="https://cloud.githubusercontent.com/assets/1725620/26186142/5864419a-3bca-11e7-804e-f558d152bc70.png">

それぞれ以下のブラウザで現象を確認しました。

* Chrome [Version 58.0.3029.110 (64-bit)]
* FireFox [52.0 (64-bit)]
* Safari [Version 10.1.1 (12603.2.4)]

**Comment by hanachin** [comment]
日本語版だけ?

**Comment by yasulab** [comment]
> 日本語版だけ?

原著でも同じ現象が確認できました
