### ISSUE TITLE
ソースコードへのリンクが貼られていない [Active Support コア拡張機能]

### ISSUE THREAD

**Issue by siman-man** [yasslab/railsguides.jp#327]
[原著](http://edgeguides.rubyonrails.org/active_support_core_extensions.html) では各ソースコードの部分にリンクが貼られていますが、日本語版ではリンクが貼られていませんでした。

リンクあり (原著)
<img width="670" alt="valid_link" src="https://cloud.githubusercontent.com/assets/1725620/26188747/f1457026-3bdb-11e7-989b-b51c6bd9ebc2.png">

リンク無し (日本語版)
<img width="666" alt="invalid_link" src="https://cloud.githubusercontent.com/assets/1725620/26188754/fdcacbe8-3bdb-11e7-8453-e8bec1089a7a.png">

**Comment by siman-man** [comment]
今の `japanese` ブランチでは、このリンクを貼る処理は取り込まれていないみたいなので、`import-upstream` ブランチで `rails/rails:master` を取り込む際にこちらの問題を修正したいと思います。

**Comment by yasulab** [comment]
報告thx! 😸

> import-upstream ブランチで rails/rails:master を取り込む際にこちらの問題を修正したい

了解です! 👍 ✨

**Comment by siman-man** [comment]
#329 の PR 内でこちらの問題を解決しましたので close します。
