### ISSUE TITLE
ブランチ名を japanese -> master に切り替える

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#335]
**目的: ブランチ毎に railsguides.jp で表示できるようにするため**

## 本家はブランチ毎にRailsGuidesのバージョニングができている

<img width="501" alt="screen shot 2017-06-07 at 10 23 53" src="https://user-images.githubusercontent.com/155807/26858319-7a32d9c0-4b6b-11e7-9a6b-bb58639a736d.png">

e.g. http://guides.rubyonrails.org/v5.0/

## 本家の GitHub Branches

<img width="243" alt="screen shot 2017-06-07 at 10 22 01" src="https://user-images.githubusercontent.com/155807/26858331-9087a750-4b6b-11e7-972a-2b1a7234e01c.png">

https://github.com/rails/rails

## 懸念点

- `japanese`というブランチ名に依存しているスクリプト (CIなど) があればそれを変更する
- yasslab/railsguides.jp の `master` ブランチの内容は無視して良い
- READMEにある画像ファイルも `japanese` ブランチ名に依存しているので変更する

**Comment by siman-man** [comment]
こちら #342 と #343 での作業で切り替えが完了しましたのでクローズしたいと思います。

**Comment by yasulab** [comment]
お疲れ様でした! 👍 ✨

**Comment by hanachin** [comment]
> 目的: ブランチ毎に railsguides.jp で表示できるようにするため

japaneseブランチのままでも表示できるようにできると思いますが、masterに変えないといけない理由あるんでしたっけ?

**Comment by yasulab** [comment]
必要性があるわけではないですね。ただ今後ブランチ毎にバージョンを切り分けるとき、独自のブランチ名をそバージョン毎にそれぞれつけるより、本家と同じブランチ名の方が他者から見て分かりやすくなるため、本家と同じブランチ名を採用しました。

**Comment by hanachin** [comment]
目的だけ読んでもわからなかったのですが、そういう理由なら合わせたほうがよさそうですね。

**Comment by yasulab** [comment]
Issue の文言変更しておきました ;) Thx for your feedback! 😸 ✨ 

> ## 背景
> 
> - 本家と同じように railsguides.jp もブランチごとにバージョニングができるようにしたい
> - 本家ではブランチ名をベースにしたコードが含まれているので、同じブランチ名だと更新が楽
> - 本家と同じブランチ名にしておけば、第３者が見たときに各ブランチの意味が汲み取りやすい
