### ISSUE TITLE
画像と説明でズレ

### ISSUE THREAD

**Issue by KxNxT** [yasslab/railsguides.jp#340]
https://railsguides.jp/association_basics.html

こちらページ内の画像(alt="belongs_to 関連付けの図")について、
前後の文ではOrderとCustomerで説明されていますが
画像ではBookとAuthorとなっております。

**Comment by yasulab** [comment]
こちら、画像があっていて、文の方が更新されたようですね。ご指摘ありがとうございます 😸 

<img width="1470" alt="screen shot 2017-06-07 at 22 05 10" src="https://user-images.githubusercontent.com/155807/26879902-ac7e63d8-4bcd-11e7-88aa-5cdbbfaa86ee.png">

**Comment by yasulab** [comment]
こちら今 diff を見てますが、大掛かりな更新になっているので対応が結構時間かかりそうです >< 💦 
しばしお待ちを...

**Comment by yasulab** [comment]
こちら対応しました! 😸
