### ISSUE TITLE
rails/rails の guides ディレクトリ以下に変更があれば通知がくるようにしたい

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#351]
RailsGuidesに更新があればそれを Idobata に通知できるようにしたい。
今は手動で対応している部分も多いですが、最終的には翻訳も自動化する。

**Comment by siman-man** [comment]
@yasulab こちらの issue ですが、クローズしても良さそうであればお願いします 🙏

**Comment by yasulab** [comment]
お、こちらもですね。指摘thx! 😆
