### ISSUE TITLE
railsguides.jp の CoC の問い合わせ先が原著になっているので変更したい

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#354]
railsguides.jp に関するものは YassLab 社が窓口になった方が良さそうだけど、rails/rails の取り込み時に
 conflict が起きないようにもしたい。うまいやり方はあるかな...? 🤔 cc/ @siman-man 

https://github.com/yasslab/railsguides.jp/blob/master/CODE_OF_CONDUCT.md

> Our Code of Conduct can be found here:
> http://rubyonrails.org/conduct/

-------------------

> Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting the project team at conduct@rubyonrails.org.

**Comment by siman-man** [comment]
この状況だと、マージ時のコンフリクトは避けられないと思いますので、取り込みスクリプト内でコンフリクトしたときに `railsguides.jp` 側の修正が優先されるように修正したいと思います。

**Comment by yasulab** [comment]
お問い合わせページを設置したため一旦 Close します! → https://railsguides.jp/contact
