### ISSUE TITLE
RailsガイドをDashで使えるようにしたい! (docsetへのコンバータを作る?)

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#37]
[![screen shot 2014-12-27 at 13 12 07](https://cloud.githubusercontent.com/assets/155807/5560409/0011f68c-8dca-11e4-81d8-0011faec61d8.png)](https://idobata.io/archives/messages/6696242)

> (思い付きレベルですが) DashというMac用のマニュアル検索ツールでは docsetというものを作成するとDashで串刺し検索できるようになります。
> 
> Rubyについては日本語のdocsetもあり、Railsも英語版のdocsetがあります。
> http://penguinlab.jp/blog/post/2290
> 
> Rails日本語版もdocsetにできたらいいなーと思った次第でした。
> Railsのdocsetには Rails Guidesだけではなく
> APIガイドも含まれているので簡単ではないですが ;-)
> 
> DashはMac用なのですが、いつの間にかWin/Linux版もできてたらしい 
> http://blog.kapeli.com/dash-for-ios-android-windows-or-linux

**Comment by kminiatures** [comment]
自分用で作りました。
https://github.com/kminiatures/railsguides.jp/tree/japanese/guides/archive
にある railsguides.docset.zip です。

Markdown から docset を作るのはわりとすぐにできました。やっつけなので docset作成スクリプトはとてもきたないですが。
検索用の Index は <h1>..<h5> を利用したので日本語じゃないとマッチしない感じです。

**Comment by yasulab** [comment]
@kminiatures さん,

反応がだいぶ遅れてしまってすみません :sweat_drops: 
また、ご報告ありがとうございます! :smile_cat: 

もしよければ PR としてまとめて頂けないでしょうか? :star2: 
WIPでも構わないので、一度 PR を開いていただければ、修正などのコミットを適宜積んでいこうかなと考えております :+1:

**Comment by kminiatures** [comment]
@yasulab PR 出させていただきました。 
https://github.com/yasslab/railsguides.jp/pull/202

**Comment by hachi8833** [comment]
@Yuppymam このissueは #202 および #205 で対応済みなので、可能であればcloseお願いしてもよろしいでしょうか？（あるいは自分がcloseします🙇）

（まだ自分がDashのビルドに成功してませんが、機能は入っています）
