### ISSUE TITLE
記入ミス？があります

### ISSUE THREAD

**Issue by kayawari** [yasslab/railsguides.jp#413]
ActiveRecord関連付けの章の4.1.4
https://railsguides.jp/association_basics.html#belongs-to%E9%96%A2%E9%80%A3%E4%BB%98%E3%81%91%E3%81%AE%E8%A9%B3%E7%B4%B0-%E9%96%A2%E9%80%A3%E4%BB%98%E3%81%91%E3%82%89%E3%82%8C%E3%81%9F%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%8C%E5%AD%98%E5%9C%A8%E3%81%99%E3%82%8B%E3%81%8B%E3%81%A9%E3%81%86%E3%81%8B%E3%82%92%E7%A2%BA%E8%AA%8D%E3%81%99%E3%82%8B

> association.nil?メソッドを使用して、関連付けられたオブジェクトが存在するかどうかを確認できます。` method:

最後の`method: `っていうのはいらない気がします。

**Comment by riseshia** [comment]
報告ありがとうございます！対応PRを #423に出しました！

**Comment by yasulab** [comment]
確認しました! Issue/PR対応ありがとうございます 😸
