### ISSUE TITLE
誤字があります

### ISSUE THREAD

**Issue by kayawari** [yasslab/railsguides.jp#414]
【該当箇所】
ActiveRecordの関連付けの章の4.1.3.2の部分
https://railsguides.jp/association_basics.html#belongs-to%E3%81%AE%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%97-includes

> LineItemから著者名(Author)を@line_item.order.authorのように直接取り出す機会が頻繁にあるのであれば、・・・・・・・・

とあると思いますが、サンプルコードではLineItem, Book, Authorの3つのクラス関連について話なので、`@line_item.order.author`ではなく`@line_item.book.author`が正しいかと思います

念のため原文も確認した所`@line_item.book.author`でした。細かいですが、ご確認いただければです。

**Comment by riseshia** [comment]
報告ありがとうございます！対応PRを #424 に出しました！

**Comment by yasulab** [comment]
確認しました! Issue/PR対応ありがとうございます 😸
