### ISSUE TITLE
ActiveRecord#increment! #decrement! が callback 対象から外れたので一覧から消したい

### ISSUE THREAD

**Issue by kawakubox** [yasslab/railsguides.jp#442]
[ここ](https://railsguides.jp/active_record_callbacks.html#%E3%82%B3%E3%83%BC%E3%83%AB%E3%83%90%E3%83%83%E3%82%AF%E3%81%AE%E5%AE%9F%E8%A1%8C)で列挙されてる callback の `increment!`, `decrement!` が Rails 5.x系から対象外となっているようです。

Ref) https://github.com/rails/rails/pull/25427

**Comment by yasulab** [comment]
Fixed by #443.

> increment!, decrement! が callback 対象から外れたため #443
