### ISSUE TITLE
association_basics :primary_keyオプションについて

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#45]
```
By convention, Rails assumes that the column used to hold the primary key of this model is `id`. You can override this and explicitly specify the primary key with the `:primary_key` option.
```

=>

```
4.2.2.7 :primary_key

Railsでは、モデルの主キーはidカラムに保存されます。:primary_keyオプションで主キーを明示的に指定することでこれを上書きすることができます。
```

```
By convention, Rails assumes that the column used to hold the primary key of this model is `id`. You can override this and explicitly specify the primary key with the `:primary_key` option.
```

=>

```
4.3.2.7 :primary_key

Railsでは、関連付けの主キーはidカラムに保存されます。:primary_keyオプションで主キーを明示的に指定することでこれを上書きすることができます。
```

`Railsでは、関連付けの主キーはidカラムに保存されます。`の箇所は`4.2.2.7`同様に`Railsでは、モデルの主キーはidカラムに保存されます。`にあわせたほうがいいと思います。

主キーそのものはレコードを一意に識別できるもので、関連付けにも利用されるというのは二次的な役割だと思います。また`関連付けの主キーはidカラムに保存されます。`では関連付けに必要な外部キーを(belongしているモデルの)idカラムに保存する、という意味と混合される気がします。

また`assumes`のニュアンス含めて

```
通常Railsでは、モデルの主キーは`id`カラムに保存されていると考えられます。
```

のように訳してはどうでしょうか？

**Comment by hachi8833** [comment]
ご指摘ありがとうございます!
By convention, Rails assumesの表現をassociation_basics.md内で統一してみました。

**Comment by yasulab** [comment]
デプロイしました! :rocket:

**Comment by yui-knk** [comment]
@yasulab  @hachi8833  確認しました。ありがとうございます。
１点気になったのですが、: primary_keyの説明が

`Railsの慣例では、モデルの主キーは`
`Railsの慣例では、関連付けの主キーは`とぶれているのは大丈夫でしょうか？　原文はまったく同じようなので。。。

**Comment by yasulab** [comment]
@yui-knk ご指摘の `:primary_key`の文章というのは、次の文章のことでしょうか? 

> Railsの慣例では、モデルの主キーは`id`カラムに保存されていることを前提とします。
> By convention, Rails assumes that the column used to hold the primary key of this model is `id`. 

> Railsの慣例では、関連付けの主キーは`id`カラムに保存されていることを前提とします。
> By convention, Rails assumes that the column used to hold the primary key of the association is `id`.

**Comment by yui-knk** [comment]
@yasulab  そうです。よく見たら原文がそれぞれ若干違いますね。`key of this mode`と`key of the association`。僕の勘違いでした。すみません。

**Comment by yasulab** [comment]
いえいえ! :smile:
また何か気になる点がありましたら気軽に報告お願いします :+1:
