### ISSUE TITLE
Action Controllerの概要 — Rails ガイド: 10.1 requestオブジェクト の表で翻訳されていない部分がある

### ISSUE THREAD

**Issue by niku** [yasslab/railsguides.jp#47]
http://railsguides.jp/action_controller_overview.html#request%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88

表の  requestのプロパティ `query_string` に対応する目的の項が

> ウRThe query string part of the URL, i.e., everything after "?".

となっています．文字化け + 翻訳がうまくいっていないように見えます．

> URL のうちクエリストリングの部分，つまり "?" から後ろ全て．

といった感じですかねえ．

**Comment by hachi8833** [comment]
発見ありがとうございます! 修正します

**Comment by yasulab** [comment]
対応しました! Issue 報告ありがとうございます :blush:

**Comment by niku** [comment]
:tea:
