### ISSUE TITLE
原著のGemfileを自動マージしつつ、Ignore したい

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#474]
どうすると良いんだろう...? 🤔 良い案を募集中です 🙏 

## 背景

cf. https://github.com/yasslab/railsguides.jp/pull/472#issuecomment-324821473

> ゆくゆくは自動で翻訳できる体制にしたいので、rails/rails の更新を自動で merge できるような構成に変わったんですよね >< 💦 
> 
> Gemfile は rails/rails でも yasslab/railsguides.jp でも使われていて、できれば(Gemfileを含め)原著をなるべく自動で取り込みつつ、原著のGemfileは railsguides.jp では使わないのでignoreできるといいんですよねぇ🤔

**Comment by hanachin** [comment]
railsguides.jp用のGemfileを分けるといいと思います

HerokuやCIでは環境変数のBUNDLE_GEMFILE指定すれば別の読むと思うので

**Comment by yasulab** [comment]
なるほど! じゃあ設定するための環境変数を決めて、PR 送る人向けに README を更新すると良さそうですね 😸 

そこまでできたらこの Issue は閉じようと思います ;)

**Comment by siman-man** [comment]
自分も `Gemfile` を `rails/rails` と `railsguides.jp` で分ける方針が良いと思います。

現状、`rails/rails` とのコンフリクトは `Gemfile` 由来のものがほとんどなので、分けれるようになると、自動マージがスムーズに出来るようになると思います。

**Comment by yasulab** [comment]
こちら、 @siman-man さんにお願いしてもよいですか? 🤔
特に期限があるわけではないので、時間あるときに対応してもらえれば 🙏

**Comment by yasulab** [comment]
環境変数周りで権限が必要であれば yasulab まで mention してもらえれば 🔔

**Comment by yasulab** [comment]
rails/rails の自動更新が10月で止まっていそう...? 🤔
https://github.com/yasslab/railsguides.jp/pull/541

Gemfile が最新版に追いついていなくて、現在は CI が止まっています >< 💦 
https://travis-ci.org/yasslab/railsguides.jp/builds/307497998

**Comment by riseshia** [comment]
最近見えないなーと思ってたら 😭

**Comment by nanophate** [comment]
https://github.com/rails/rails/commits/master/actionpack/lib/action_dispatch/http/cache.rb をみながらcommitで影響がありそうな、ライブラリーが追加されていないか確認しました。`uglifier`や`cache`系を入れて見ましたが、上手く動きませんでした。他に何が原因があるそうです😢

**Comment by yasulab** [comment]
> Gemfile が最新版に追いついていなくて、現在は CI が止まっています >< 💦
> https://travis-ci.org/yasslab/railsguides.jp/builds/307497998

CIが修正されました! 対応 thx 😸 
自動更新されることが確認できたらこちらの Issue を閉じますね ;)

**Comment by hanachin** [comment]
コミット読んでいたのですがGemfileからyasslab/Gemfile読んでしまうと今問題のGemfileのコンフリクトは解消されるかもしれませんがgemが競合してbundle installコケるなどの問題は残ってしまいそうです。
https://github.com/yasslab/railsguides.jp/pull/546/commits/a443ddd81fd33cdb5c279c0ebbe3515977c9c03d

- Gemfileからyasslab/Gemfileを読んでる部分を消してGemfile.lockを本家のものに戻す
- `BUNDLE_GEMFILE=yasslab/Gemfile bundle install`して`yasslab/Gemfile.lock`をつくる
- Herokuとtravis-ciで`BUNDLE_GEMFILE`の環境変数をyasslab/Gemfileに変える

みたいな対応をしたほうがよさそうです

**Comment by siman-man** [comment]
仰る通り、上記の問題は残ったままです（Gemfile が更新された時にコンフリクトする可能性）

なので、今回の対応は一時的なものと認識しています。

本来であれば、yasslab/Gemfile と rails/Gemfile を分けるべきなのですが、現状の問題として分けて `bundle install` を行った時に `bundle exec rake assets:precompile` のコマンドが失敗してしまうという問題がのこっており、この失敗の原因の特定に時間がかかりそうと判断して今回の対応を取りました。

```
$ BUNDLE_GEMFILE=yasslab/Gemfile bundle exec rake -f yasslab/Rakefile assets:precompile
Configuration file: /Users/siman/yasslab/railsguides.jp/_config.yml
       Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
           Cleaner: Nothing to do for ./_site.
           Cleaner: Nothing to do for ./guides/output/ja/.jekyll-metadata.
           Cleaner: Nothing to do for ./guides/output/ja/.sass-cache.
/Users/siman/.rbenv/versions/2.4.1/bin/ruby rails_guides.rb
/Users/siman/yasslab/railsguides.jp/actionpack/lib/action_dispatch/http/response.rb:91:in `<class:Response>': undefined method `cache_control' for class `ActionDispatch::Response' (NameError)
	from /Users/siman/yasslab/railsguides.jp/actionpack/lib/action_dispatch/http/response.rb:37:in `<module:ActionDispatch>'
	from /Users/siman/yasslab/railsguides.jp/actionpack/lib/action_dispatch/http/response.rb:8:in `<top (required)>'
	from /Users/siman/yasslab/railsguides.jp/actionpack/lib/action_controller/metal/live.rb:3:in `require'
	from /Users/siman/yasslab/railsguides.jp/actionpack/lib/action_controller/metal/live.rb:3:in `<top (required)>'
	from /Users/siman/yasslab/railsguides.jp/actionpack/lib/action_controller.rb:6:in `require'
	from /Users/siman/yasslab/railsguides.jp/actionpack/lib/action_controller.rb:6:in `<top (required)>'
	from /Users/siman/yasslab/railsguides.jp/guides/rails_guides/generator.rb:8:in `require'
	from /Users/siman/yasslab/railsguides.jp/guides/rails_guides/generator.rb:8:in `<top (required)>'
	from /Users/siman/yasslab/railsguides.jp/guides/rails_guides/generator_ja.rb:1:in `require'
	from /Users/siman/yasslab/railsguides.jp/guides/rails_guides/generator_ja.rb:1:in `<top (required)>'
	from rails_guides.rb:13:in `require'
	from rails_guides.rb:13:in `<main>'
rake aborted!
```

エラーの原因については yasslab/Gemfile に切り分けた時に何か gem が漏れている可能性があるのですが、まだ特定は出来ていません。
