### ISSUE TITLE
「Railsエンジン入門」ページの誤訳

### ISSUE THREAD

**Issue by 5t111111** [yasslab/railsguides.jp#48]
[「Railsエンジン入門」ページ](http://railsguides.jp/engines.html)の[「3.1 Articleリソースを生成する」](http://railsguides.jp/engines.html#articleリソースを生成する)に以下の記述があります。

> デフォルトでは、scaffoldで生成されたスタイルは適用されません。これは、エンジンのレイアウトファイルapp/views/layouts/blorgh/application.html.erbがデフォルトでは読み込まれないようになっているためです。

この文章は `app/views/layouts/blorgh/application.html.erb` がデフォルトで読み込まれないように受け取れますが、原文では以下のようになっています。

> By default, the scaffold styling is not applied to the engine because the engine's layout file, app/views/layouts/blorgh/application.html.erb, doesn't load it. 

意味が変わってしまっているようなので誤訳かと思います。
ご確認ください。

**Comment by hachi8833** [comment]
ご指摘ありがとうございます! 確認・修正しておきます。

**Comment by yasulab** [comment]
ご指摘ありがとうございます! 対応しました :white_check_mark: :smile:
