### ISSUE TITLE
Groongaを使ってRailsガイドの全文検索を可能にしたい

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#49]
先日の [Heroku Meetup 新年会](http://herokujp.doorkeeper.jp/events/18242)で @kou さんとお会いすることができ、「テキストデータを[Groonga](http://groonga.org/)に渡すと(わりと簡単に)全文検索ができますよ」ということをお聞きしたので、ちょっと時間が出来たときに作ってみたいなと思っております :star2:

**Comment by kou** [comment]
やりましょう！

**Comment by yasulab** [comment]
はい! やってみます! :smile_cat:
