### ISSUE TITLE
各リンクをテストするスクリプト

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#5]
(#4 から)

各章へのリンクや、章内の各節へのリンクをチェックするテストがあると、動作確認が楽になりそう。

**Comment by yasulab** [comment]
社内で使っているRailsチュートリアルのテストスクリプトの例をGistに晒してみました :see_no_evil: 

Railsチュートリアルのテストスクリプト例
https://gist.github.com/yasulab/13978a3f56d3625d4440
(Implemented by and thanks to @hanachin for his open-mind.)

Railsガイドのテストについても、 :arrow_up: こんな感じのテストを想定しています。

**Comment by yui-knk** [comment]
#101  で対応しました

**Comment by yasulab** [comment]
対応ありがとうございました :blush:
