### ISSUE TITLE
constant_autoloading_and_reloading

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#51]
`INFO. From then on, what happens to the constant and the instance does not matter.`

`INFO. これより先、定数とインスタンスで何が起きるかは問題ではありません。`

の箇所ですが、`From then on`は`一度無名クラスや無名モジュールに名前が与えられた後は`のほうが具体的で分かりやすいと思います。

**Comment by hachi8833** [comment]
修正しました。ありがとうございます!

**Comment by yui-knk** [comment]
GTT確認しました。ありがとうございます。
