### ISSUE TITLE
修正時に参照する原本のversionについて

### ISSUE THREAD

**Issue by rochefort** [yasslab/railsguides.jp#520]
https://github.com/yasslab/railsguides.jp/blame/master/guides/source/ja/action_view_overview.md#L83
```
ホワイトスペースを取り除きたい場合は<%- および -%>を通常の<% および %>と交互にご使用ください
```
`交互にご使用ください`のところは誤訳のようなので修正しようかと思ったのですが、
修正時に参照する原本のversionはどれを見れば良いのでしょうか？

/guides/source/action_view_overview.md

**Comment by yasulab** [comment]
現状では最新版が自動的に取り込まれる仕組みになっています。なので、 https://github.com/yasslab/railsguides.jp/tree/master/guides/source にある内容が最新 (実質的には http://edgeguides.rubyonrails.org/ と同じ) になっているはずですので、こちらを原著として参照する形になります :)

**Comment by rochefort** [comment]
わかりました。
twitterでも個別に聞いてしまいましたが、現状最新版への追随するという対応は滞っているようなので
積極的に最新版にuploadせずに、明らかな誤訳や間違いに気づいた場合のみPR送らせていただくようにします。
