### ISSUE TITLE
Getting started における誤訳

### ISSUE THREAD

**Issue by spinute** [yasslab/railsguides.jp#540]
https://railsguides.jp/getting_started.html#モデル同士を関連付ける の第2パラグラフ、訳文「Comment モデル (app/models/comment.rb) 内のコードに既に書かれていたように、1つの記事には1つのコメントが属しています。」の後半は、原文"each comment belong to an Article"と異なる意味になっているように思います。

**Comment by spinute** [comment]
#12 と同様の指摘ですが、箇所が異なります。

**Comment by yasulab** [comment]
Thx for your report! 😸
