### ISSUE TITLE
「Active Support コア拡張機能」の「1.1 単体のActive Supportサポート」について

### ISSUE THREAD

**Issue by taki3** [yasslab/railsguides.jp#542]
「1.1 単体のActive Supportサポート」というタイトルになっていますが、「1.1 単体のActive Support」だと思います。

cf. https://railsguides.jp/active_support_core_extensions.html#%E5%8D%98%E4%BD%93%E3%81%AEactive-support%E3%82%B5%E3%83%9D%E3%83%BC%E3%83%88

**Comment by yasulab** [comment]
Thx! 😸
