### ISSUE TITLE
typo: 'bin/rails db:migrate'と書かれている部分の修正

### ISSUE THREAD

**Issue by starcharles** [yasslab/railsguides.jp#544]
本家のほうのタイプミスもあったのでPRしたのですが、

rails/guides/source/plugins.md
において

https://github.com/starcharles/rails/blob/master/guides/source/plugins.md#add-a-class-method

```
$ cd test/dummy
$ bin/rails db:migrate
```
となっているところがありました。
正しくはbin/rake db:migrateだと思います。

**Comment by starcharles** [comment]
必要あればこちらもプルリク出します

**Comment by yasulab** [comment]
> 必要あればこちらもプルリク出します

よければぜひお願いしたいです! 😸

**Comment by starcharles** [comment]
bin/rails db:migrate　はRails5以降では使えるコマンドなのでタイポでは無いという回答でした。
Rails4でしか試していなかったのでこちらのミスでした。

https://github.com/rails/rails/pull/31107#issuecomment-343195680

**Comment by yasulab** [comment]
ではこちらの Issue は閉じちゃいますね ;) 報告ありがとうございます！😆
