### ISSUE TITLE
起源?

### ISSUE THREAD

**Issue by znz** [yasslab/railsguides.jp#545]
https://railsguides.jp/5_1_release_notes.html#action-cable の「起源の同じ接続をデフォルトで許可 (commit)」の「起源」は origin の訳だとしたら、「オリジン」か「生成元」が一般的で「起源」とは言わないと思います。 https://ja.wikipedia.org/wiki/%E5%90%8C%E4%B8%80%E7%94%9F%E6%88%90%E5%85%83%E3%83%9D%E3%83%AA%E3%82%B7%E3%83%BC

原文はどうなっているのかと思って http://guides.rubyonrails.org/5_1_release_notes.html#action-cable をみると該当する段落自体がないようなので、削除するのが良いのかもしれません。

**Comment by yasulab** [comment]
指摘ありがとうございます! 😸  削除しておきました ✂️ ✨
