### ISSUE TITLE
typo 「XSSは最もよく発生しする」

### ISSUE THREAD

**Issue by mame** [yasslab/railsguides.jp#547]
https://github.com/yasslab/railsguides.jp/blob/master/guides/source/ja/security.md#クロスサイトスクリプティング-xss

の冒頭、「INFO: XSSは最もよく発生しするWebセキュリティ上の脆弱性であり」の「しする」は「する」の typo だと思います。

**Comment by yasulab** [comment]
ご指摘ありがとうございます! 修正しました 😸
