### ISSUE TITLE
アセットパイプラインの require_self の説明

### ISSUE THREAD

**Issue by scivola** [yasslab/railsguides.jp#549]
https://railsguides.jp/asset_pipeline.html#%E3%83%9E%E3%83%8B%E3%83%95%E3%82%A7%E3%82%B9%E3%83%88%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%A8%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%86%E3%82%A3%E3%83%96
において，require_self の説明が

> 上の例ではrequire_selfが使用されています。このディレクティブは、require_self呼び出しが行われたその場所にCSSファイルがあれば読み込みます。

となっています。

しかし，require_self は CSS ファイルを探しに行って取り込むものではなく，require_self が書かれたファイルの中のスタイル記述を取り込むものではないでしょうか。

原文は

> In this example, require_self is used. This puts the CSS contained within the file (if any) at the precise location of the require_self call.

となっていて，「CSSファイル」とは書かれていません。

**Comment by riseshia** [comment]
まずPR作って見ました。 #551

**Comment by yasulab** [comment]
Fixed by https://github.com/yasslab/railsguides.jp/pull/551
