### ISSUE TITLE
constant_autoloading_and_reloading(解決アルゴリズム)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#57]
この中ででてくる"ancestors"は[クラス、モジュールのスーパークラスとインクルードしているモジュール](http://docs.ruby-lang.org/ja/2.1.0/method/Module/i/ancestors.html)のことだと思います。
現在の"祖先"という訳に注釈をつけてみてはどうでしょうか？

**Comment by hachi8833** [comment]
ありがとうございます。GTTで以下のようにしてみましたが、いかがでしょうか。

> それらの要素の先祖は探索されない (訳注: 本章で言う先祖 (ancestors) とは[クラス、モジュールのスーパークラスとインクルードしているモジュール](http://docs.ruby-lang.org/ja/2.1.0/method/Module/i/ancestors.html)のことです)。

**Comment by yui-knk** [comment]
確認しました！

**Comment by yui-knk** [comment]
自分の張ったリンクが2.1.0のものだったので、2.2.0にGTT上で修正しました
