### ISSUE TITLE
Rails セキュリティガイドのセッションIDの項目の翻訳提案

### ISSUE THREAD

**Issue by umyuu** [yasslab/railsguides.jp#598]
素晴らしいドキュメントの公開をありがとうございます。

[Rails セキュリティガイド](https://railsguides.jp/security.html)について１点指摘事項があります。
■[訳文](https://railsguides.jp/security.html)
2.2 セッションid
セッションidは、32バイトのMD5ハッシュ値です。
1つのセッションidは、ランダムな文字列のハッシュ値で構成されています。このランダムな文字列は、現在時刻、0から1までの乱数、Rubyインタープリタのプロセスid (これも基本的には乱数です)、および一定の文字列です。現時点では、Railsのセッションidにブルートフォース攻撃を行なうことは不可能です。MD5は現在まで破られていませんが、若干の衝突が発生しているため、同じハッシュ値を異なる入力テキストから生成することは「理論的には」不可能ではありません。しかしこれがセキュリティ上の脅威になったことはこれまでありません。

■[原文](http://guides.rubyonrails.org/security.html)
2.2 Session ID
The session ID is a 32-character random hex string.
The session ID is generated using SecureRandom.hex which generates a random hex string using platform specific methods (such as OpenSSL, /dev/urandom or Win32) for generating cryptographically secure random numbers. Currently it is not feasible to brute-force Rails' session IDs.

■提案文
2.2 セッションid
セッションidは、32桁の16進数のランダムな文字列です。
セッションidは、[SecureRandom.hex](https://docs.ruby-lang.org/ja/latest/method/SecureRandom/s/hex.html)、暗号で安全な乱数を生成するためのプラットフォーム固有のメソッド（OpenSSL、/dev/urandom、またはWin32など）を使用してランダムな16進文字列を生成するために使用されます。現時点では、Railsのセッションidにブルートフォース攻撃を行なうことは不可能です。

以上です。

**Comment by riseshia** [comment]
ありがとうございます！該当PR用意しましたXD

**Comment by umyuu** [comment]
該当PRを拝見させていただきました。
NOTE: _セッションidは、32バイトのMD5ハッシュ値です。_
PRの上の行にあるNOTEの部分もMD5ハッシュ値ではないので、修正する必要があるかと。
すみません、issuseを起票するときに気づきませんでした・・・
