### ISSUE TITLE
Railsガイドを差分更新できる状態にしたい 

### ISSUE THREAD

**Issue by himajin315** [yasslab/railsguides.jp#602]
# 背景
Railsガイドを差分更新できる状態にしたい。現状ではどこに差分があって、どこを更新すれば良いのかがわからない。これらの差分情報を明確にし、差分更新できる状況に仕上げたい。

# 現状

<img width="1006" alt="2018-01-17 14 44 30" src="https://user-images.githubusercontent.com/1221303/35028307-c4e42824-fb98-11e7-8347-ff5124e2c0b7.png">

- [rails/rails の master](https://github.com/rails/rails/) のバージョンは `v5.2.0.beta2`である(2018/01/17)
- version 4.2 までは原文が一致していることは確認できている
- version 5.0 までは日本語翻訳できているが、それ以降は訳文が少しずつ追加されている

# やること
v5.2.0.beta2とv4.2.10の差分を確認する

## 確認作業
1. ファイル名のリンクから差分のコミットを開く
1. コミットメッセージに書いてある対応する訳文ファイルのリンクを開く
1. 原文の差分と訳文を読み比べて、原文の差分に変更の要否をコメントする
1. コメントしたリンクを訳文にコメントアウトするような形で書き残す

### 例

例えば以下の場合

- [ ] [guides/source/security.md](https://github.com/yasslab/railsguides.jp/commit/87a8366968ac1972f44b4803e3841fe2475bf916)

コミットを開く
https://github.com/yasslab/railsguides.jp/commit/87a8366968ac1972f44b4803e3841fe2475bf916

対応する訳文ファイルのリンクを開く(commit messageに記述されている)
https://github.com/yasslab/railsguides.jp/edit/5.1_update/guides/source/ja/security.md

読み比べて、対応の要否を次の絵文字を先頭に付けてコメントする

- 必要な場合は `:construction:`
- 不要の場合は `:white_check_mark: ` 
  
<img width="515" alt="d618aef1-be88-8db2-a87b-5748b12e477d" src="https://user-images.githubusercontent.com/1221303/35028935-d674ed8c-fb9b-11e7-8072-609c807ed410.png">

[:point_up:GitHubサンプルコメント: 要変更](https://github.com/yasslab/railsguides.jp/commit/87a8366968ac1972f44b4803e3841fe2475bf916#r26467780)

<img width="516" alt="7f081f86-7128-b987-b13c-1dba755ccfab" src="https://user-images.githubusercontent.com/1221303/35028942-de704af4-fb9b-11e7-84c3-91c9050d76fd.png">

[:point_up:GitHubサンプルコメント: 変更不要](https://github.com/yasslab/railsguides.jp/commit/87a8366968ac1972f44b4803e3841fe2475bf916#r26467833)

訳文にコメントしたリンクを書く `TODO: (コメントしたリンク)`

<img width="640" alt="screen shot 2018-01-18 at 18 24 33" src="https://user-images.githubusercontent.com/6015450/35090413-f1926c66-fc7c-11e7-8b5b-1f1e30f99dd6.png">

## 進捗を記録する方法

確認作業を始めたら自分のアカウント名をファイル名の横に表示する

- [ ] @hanachin_:  [guides/source/2_2_release_notes.md](https://github.com/yasslab/railsguides.jp/commit/3755c6c7c1c062067f22f9382f4fb92f6ebe06da)

確認が終わったらチェックを付ける

- [x] @hanachin_:  [guides/source/2_2_release_notes.md](https://github.com/yasslab/railsguides.jp/commit/3755c6c7c1c062067f22f9382f4fb92f6ebe06da)

訳されていないときは確認作業をせずに、`:fast_forward:`をつけてチェックを入れる

- [x] @hanachin_: :fast_forward:  [guides/source/2_2_release_notes.md](https://github.com/yasslab/railsguides.jp/commit/3755c6c7c1c062067f22f9382f4fb92f6ebe06da)

## 残り作業

- [x] @nanophate: :fast_forward: [guides/source/2_2_release_notes.md](https://github.com/yasslab/railsguides.jp/commit/3755c6c7c1c062067f22f9382f4fb92f6ebe06da)
- [x] @nanophate: :fast_forward: [guides/source/2_3_release_notes.md](https://github.com/yasslab/railsguides.jp/commit/1fe90ff7a57f856713405dbd1063d3ce87551fab)
- [x] @nanophate: :fast_forward: [guides/source/3_0_release_notes.md](https://github.com/yasslab/railsguides.jp/commit/b630695680d8474d674818c5b2e978e27263ac38)
- [x] @nanophate: :fast_forward: [guides/source/3_1_release_notes.md](https://github.com/yasslab/railsguides.jp/commit/0e319dc0713c2c137ab1c538c21f08506b4ce9c8)
- [x] @nanophate: :fast_forward: [guides/source/3_2_release_notes.md](https://github.com/yasslab/railsguides.jp/commit/34d18f0e7baf875eb3c381fc5dbe4fb7a61ffed6)
- [x] @nanophate: :fast_forward: [guides/source/4_0_release_notes.md](https://github.com/yasslab/railsguides.jp/commit/c35c9c4ab39fe8378bd608994052a11a3079d16b)
- [x] @nanophate: :fast_forward: [guides/source/4_1_release_notes.md](https://github.com/yasslab/railsguides.jp/commit/f3e0c8f3eafe560379a9cecaceb8a07702b10f68)
- [x] @nanophate: :fast_forward: [guides/source/4_2_release_notes.md](https://github.com/yasslab/railsguides.jp/commit/72d29013d96d73f5fb8723e6b345148567276812)
- [x] @nanophate: :fast_forward: [guides/source/5_0_release_notes.md](https://github.com/yasslab/railsguides.jp/commit/ce37bce1e2791d1bdce84c0ebfaf9289b8f49aaa)
- [x] @nanophate: :fast_forward: [guides/source/5_1_release_notes.md](https://github.com/yasslab/railsguides.jp/commit/c07cd816f0bbf371627de191152353af9ca07f1a)
- [x]  @nanophate: :fast_forward: [guides/source/5_2_release_notes.md](https://github.com/yasslab/railsguides.jp/commit/99d990f989dc48349f2eb12733a0968ad415e3a1)
- [x] @himajin315:  [guides/source/action_cable_overview.md](https://github.com/yasslab/railsguides.jp/commit/194802dc04a0366eb55cc619f1b37843917b9944)
- [x] @nanophate: [guides/source/action_controller_overview.md](https://github.com/yasslab/railsguides.jp/commit/d8553fd65f43b4fec2ca9183d62a6d491936a9ff)
- [x] @himajin315: [guides/source/action_mailer_basics.md](https://github.com/yasslab/railsguides.jp/commit/b5f9267a1bed1fe868df2d35b17657202fd4a1e0)
- [x] @nanophate: [guides/source/action_view_overview.md](https://github.com/yasslab/railsguides.jp/commit/3dc4225f5516c73b2a3cea63c34636897b50af66)
- [x] @nanophate: [guides/source/active_job_basics.md](https://github.com/yasslab/railsguides.jp/commit/5d56c756f37f2fe595bffb234affdbf0d801afaf)
- [x] @nanophate: [guides/source/active_model_basics.md](https://github.com/yasslab/railsguides.jp/commit/0ef590f7382008f2823e75d5b5dbef6cf606afff)
- [x] @himajin315: [guides/source/active_record_basics.md](https://github.com/yasslab/railsguides.jp/commit/b4ba6580c40d67f90f4abbb9415ee3c9bce6c95a)
- [x] @nanophate: [guides/source/active_record_callbacks.md](https://github.com/yasslab/railsguides.jp/commit/da266672565fc5d8c4ecde348ea61dfb524dd9fc)
- [x] @nanophate: [guides/source/active_record_migrations.md](https://github.com/yasslab/railsguides.jp/commit/1adde655a309fbc308a64d923af3f4857e367636)
- [x] @nanophate: ⏩ [guides/source/active_record_postgresql.md](https://github.com/yasslab/railsguides.jp/commit/8ec8e1236b007e6b65519fd13caf509421fc21f2)
- [x] @nanophate: [guides/source/active_record_querying.md](https://github.com/yasslab/railsguides.jp/commit/68b89f110ef678fc35b99c559c1426c00f82583c)
- [x] @himajin315: [guides/source/active_record_validations.md](https://github.com/yasslab/railsguides.jp/commit/78c92275164cd4ea7c567fbc7ed831e44e3bdd56)
- [x] @himajin315: [guides/source/active_support_core_extensions.md](https://github.com/yasslab/railsguides.jp/commit/9f65311706916a719dfee6198a26984215341fb2)
- [x] @himajin315: [guides/source/active_support_instrumentation.md](https://github.com/yasslab/railsguides.jp/commit/54eb3512fb610c7db0f7601863e9522a06281e79)
- [x] @himajin315: [guides/source/api_app.md](https://github.com/yasslab/railsguides.jp/commit/bc868b0eb35712469adb049f913add99f3986ae1)
- [x] @himajin315: [guides/source/api_documentation_guidelines.md](https://github.com/yasslab/railsguides.jp/commit/22e9c0991a59c9b0c2424167e4bd9c2604db886c)
- [x] @himajin315: [guides/source/asset_pipeline.md](https://github.com/yasslab/railsguides.jp/commit/7da630774aba723c22be9455d69551c1ae57a82e)
- [x] @nanophate: [guides/source/association_basics.md](https://github.com/yasslab/railsguides.jp/commit/192f67bc3563a54d1bc406bce076be80a6ff0b1e)
- [x] @nanophate: [guides/source/autoloading_and_reloading_constants.md](https://github.com/yasslab/railsguides.jp/commit/8f91256213101bcb922022bf01d0abccaa2df76e)
- [x] @nanophate: [guides/source/caching_with_rails.md](https://github.com/yasslab/railsguides.jp/commit/d2e8af6cf0dbc3374c8553c362e90b75604b9765)
- [x] @nanophate: [guides/source/command_line.md](https://github.com/yasslab/railsguides.jp/commit/8b5e95c7b8f875f624604430e318f3cd39e613e3)
- [x] @nanophate: [guides/source/configuring.md](https://github.com/yasslab/railsguides.jp/commit/18328847f801fa8827726dd67a4825951875e9d5)
- [x] @nanophate: [guides/source/contributing_to_ruby_on_rails.md](https://github.com/yasslab/railsguides.jp/commit/5af4c1906ec28732e3d0ab263c2a99705099e805)
- [x] @himajin315: [guides/source/debugging_rails_applications.md](https://github.com/yasslab/railsguides.jp/commit/e70a8d2cd10b21894109a4d3fb5258e99f276a25)
- [x] @himajin315: [guides/source/development_dependencies_install.md](https://github.com/yasslab/railsguides.jp/commit/1c85afdff9f24b3b4281149282fd5b95a93db3b1)
- [x] @himajin315: [guides/source/engines.md](https://github.com/yasslab/railsguides.jp/commit/a9e6632d185dd7436d8c4eca38ca52e047d1eacc)
- [x] @himajin315: [guides/source/form_helpers.md](https://github.com/yasslab/railsguides.jp/commit/a7b8e7f5afaa54bf0a5bb643ee6994496f1293e0)
- [x] @himajin315: [guides/source/generators.md](https://github.com/yasslab/railsguides.jp/commit/c4e8f58f47fc31dd5479cc0f2a30be5209e1cb86)
- [x] @himajin315: [guides/source/getting_started.md](https://github.com/yasslab/railsguides.jp/commit/6b81f397560a02995119d707a6c2d43d1f231c24)
- [x] @himajin315: [guides/source/i18n.md](https://github.com/yasslab/railsguides.jp/commit/c8ce87b4bd98e0f33d43f3e3257adfc471bc7910)
- [x] @himajin315: [guides/source/initialization.md](https://github.com/yasslab/railsguides.jp/commit/f09bc92c8c797471a10b6950b096bea7f0624695)
- [x] @himajin315: [guides/source/layouts_and_rendering.md](https://github.com/yasslab/railsguides.jp/commit/af71866016cdb4780bd037998380d89f57bdad84)
- [x] @himajin315: [guides/source/maintenance_policy.md](https://github.com/yasslab/railsguides.jp/commit/5b41453ab00b1b881d35b10adfa40e88bab85dbf)
- [x] @himajin315: [guides/source/plugins.md](https://github.com/yasslab/railsguides.jp/commit/f49f07ca37e4b87b53df8ae0bc4de72a2e407a88)
- [x] @himajin315: [guides/source/rails_application_templates.md](https://github.com/yasslab/railsguides.jp/commit/001f5a070e278a3f4175c4d57fa4f8b4d5d506c1)
- [x] @himajin315: [guides/source/rails_on_rack.md](https://github.com/yasslab/railsguides.jp/commit/191714ea977bb6c5c6f19fb2f4da93be616df2b3)
- [x] @himajin315: [guides/source/routing.md](https://github.com/yasslab/railsguides.jp/commit/6a06d9ec3f4dd834faaff20e83496bc2f2c6be9e)
- [x] @himajin315: [guides/source/ruby_on_rails_guides_guidelines.md](https://github.com/yasslab/railsguides.jp/commit/f1358bde637528612973c09be4c797100d808bfb)
- [x] @nanophate: [guides/source/security.md](https://github.com/yasslab/railsguides.jp/commit/87a8366968ac1972f44b4803e3841fe2475bf916)
- [x] @himajin315: [guides/source/testing.md](https://github.com/yasslab/railsguides.jp/commit/4ea09d8c1decf178d4135042d30cf9824000df76)
- [x] @nanophate: ⏩ [guides/source/threading_and_code_execution.md](https://github.com/yasslab/railsguides.jp/commit/6b4b6d2f0483303a042b6dccc5e05c6ddc7079d9)
- [x] @nanophate: [guides/source/upgrading_ruby_on_rails.md](https://github.com/yasslab/railsguides.jp/commit/e22b3857e6d04eedf4771755a4fcdb04eb69c7e0)
- [x] @nanophate: [guides/source/working_with_javascript_in_rails.md](https://github.com/yasslab/railsguides.jp/commit/bca67835841f9279a20d3526d81f1aed40e213f8)

**Comment by nanophate** [comment]
差分検知作業が終わったのでクローズしますm(_ _)m
