### ISSUE TITLE
constant_autoloading_and_reloading(Autoloading Algorithms)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#62]
```
modulus some additional directory lookups we are going to cover soon.
```

```
モジュールの探索対象となるその他のディレクトリについては後述します。●
```

ですが、"modulus"は辞書通り"標準"という意味ではないでしょうか。

`PostsController`内の`Post`定数を探索するとき、`app/controllers/posts_controller/post.rb`ファイルと`app/controllers/post.rb`ファイル以外に`app/controllers/posts_controller/post`ディレクトリなども追加で探索することを指しているのではないでしょうか。

**Comment by hachi8833** [comment]
以下のように修正しました。
> 探索対象となるその他の標準的なディレクトリについては後述します。
