### ISSUE TITLE
constant_autoloading_and_reloading(Autoloading Algorithms)2

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#63]
```
INFO. `'Constant::Name'.underscore` gives the relative path without extension of the file name where `Constant::Name` is expected to be defined.
```

```
INFO. `'Constant::Name'.underscore`は、`Constant::Name`が定義されていると期待されている場所でファイル拡張子抜きの相対パスを返します。
```

[`underscore`メソッド](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html)は以下のように働きます。

```
'ActiveModel::Errors'.underscore # => "active_model/errors"
```

ここではwhereはthe file nameを指していると思います。
よって「`'Constant::Name'.underscore`は、`Constant::Name`が定義されていると期待されているファイルへの相対パスを返します(ただしファイル名からは拡張子が抜かれます)。」のような訳はどうでしょうか？　丸括弧をはずした訳がいいのですが・・・

**Comment by hachi8833** [comment]
以下のように修正しました。
>'Constant::Name'.underscoreは、Constant::Nameが定義されていると期待されているファイルへの相対パスを返します。このファイル名には拡張子は含まれません。

**Comment by yui-knk** [comment]
すみません、僕の訳に`が抜けていたようなのでGTTでは補いました！
