### ISSUE TITLE
action_controller_overview(10.2 The responseオブジェクト)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#64]
```
The response object is not usually used directly, but is built up during the execution of the action and rendering of the data that is being sent back to the user, but sometimes - like in an after filter - it can be useful to access the response directly. Some of these accessor methods also have setters, allowing you to change their values.
```

```
通常、responseオブジェクトを直接使用することはありません。このオブジェクトの内容は、クライアントに送り返される、アクションの実行中およびデータの描画 (レンダリング) ですが、このオブジェクトに直接これらのアクセサの中にはセッターで値を変更できるものもあります。
```

"is built up during ~"の箇所ですが、"アクション(コントローラのアクションメソッド)の実行を通じてresponseオブジェクトが構築されていく"という意味ではないでしょうか。そのあとの"and rendering"がどこからつながっているのか分からないので、その後の訳が適切かは自分には判断できませんが。。。

"but sometimes - like in an after filter - it can be useful to access the response directly"が訳しもれているので、"例えばafter filter内など、responseオブジェクトを直接操作したい(responseオブジェクトの値を直接操作したい?)ときもあります"のような訳がいいのではないでしょうか？

"Some of these accessor methods also have setters, allowing you to change their values."のところの訳が少々ぎこちなく感じます。おそらくaccessor methodsにはwriterもreaderもあることから、"Some of these ~"と書かれているのだと思いますので、"responseオブジェクトのアクセサメソッドのなかにはセッターをもつものもあり、値を直接変更できるものもあります。"のような訳がいいのではないでしょうか。

まとめると

```
通常、responseオブジェクトを直接使用することはありません。アクションの実行を通じてresponseオブジェクトが構築されていき、クライアントに送り返されるデータを描画 (レンダリング)します。例えばafter filter内など、responseオブジェクトを直接操作したいときもあります。responseオブジェクトのアクセサメソッドのなかにはセッターをもつものもあり、値を直接変更できるものもあります。
```

のような訳です（もう少し明示的に接続した文章にしたい・・・）。
確認よろしくお願いします！

**Comment by hachi8833** [comment]
チェックありがとうございました! 訳文が途中からちぎれていましたので、いただいた試訳をベースに修正しました。

**Comment by yui-knk** [comment]
確認しました。ありがとうございます！
