### ISSUE TITLE
未翻訳のドキュメント : threading and code execution を翻訳したい

### ISSUE THREAD

**Issue by nanophate** [yasslab/railsguides.jp#653]
## やりたいこと

次の翻訳されていないドキュメントを翻訳したいです。
英文のドキュメント: [guides/source/threading_and_code_execution.md](https://github.com/rails/rails/blob/master/guides/source/threading_and_code_execution.md)

#### 参考
_翻訳対象のドキュメント : [guides/source/ja/threading_and_code_execution.md](https://github.com/yasslab/railsguides.jp/blob/5.1_update/guides/source/ja/threading_and_code_execution.md) (NOT FOUNDのファイルが表示されます)_

**Comment by hachi8833** [comment]
https://github.com/yasslab/railsguides.jp/pull/739 にて翻訳しました。
確認、マージ、closeをお願いします @nanophate
