### ISSUE TITLE
未翻訳のドキュメント : 5.1 release notes を翻訳したい 

### ISSUE THREAD

**Issue by nanophate** [yasslab/railsguides.jp#654]
## やりたいこと

次の翻訳されていないドキュメントを翻訳したいです。
英文のドキュメント: [guides/source/5_1_release_notes](https://github.com/rails/rails/blob/master/guides/source/5_1_release_notes.md)

#### 参考
_翻訳対象のドキュメント : [guides/source/ja/5_1_release_notes](https://github.com/yasslab/railsguides.jp/blob/5.1_update/guides/source/ja/5_1_release_notes.md) (NOT FOUNDのファイルが表示されます)_

**Comment by hachi8833** [comment]
これは翻訳済みですね https://railsguides.jp/5_1_release_notes.html
closeしておきます

**Comment by yasulab** [comment]
ですね! Close ありがとうございます 😸
