### ISSUE TITLE
Railsガイドを5.1に翻訳したい

### ISSUE THREAD

**Issue by nanophate** [yasslab/railsguides.jp#655]
## やりたいこと
Railsガイドを5.1に翻訳したい。

https://github.com/yasslab/railsguides.jp/projects/1 で進捗の管理をしています。
1. 翻訳をしたいPRを `Translation Ready` のカラムから選んでください。
2. 選んだPRにAssignesに自分を追加して下さい。
3. 翻訳作業を進め、翻訳だきたら Reviewerに @yasulab を assignし、@yasulab宛にメンションを飛ばしてください。
4. ReviewでLGTM確認と同時にマージされます！おめでとうとございます! 🎉

**Comment by yasulab** [comment]
こちら Rails 5.1 対応は済んでいるので閉じちゃいますね ;)
