### ISSUE TITLE
Ruby2.4.1のアップデート

### ISSUE THREAD

**Issue by AnaTofuZ** [yasslab/railsguides.jp#673]
## 背景

脆弱性関連のアップデートが入った為にアップデートしたい
https://www.ruby-lang.org/ja/news/2018/03/28/ruby-2-4-4-released/

## 終了条件

- railsguideのRubyを2.4.1から最新の2.4.4にアップデートする

**Comment by yasulab** [comment]
Heroku 側が対応していれば Ruby 2.5 系の最新版でも良いかも ;)

**Comment by AnaTofuZ** [comment]
Heroku側では2.5.1 (2.5系の最新版)もサポートしているようなのでこちらで行きたいと思います!
cf. https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
