### ISSUE TITLE
Railsルーティングの「単数形リソース」のオプションが原文と異なる

### ISSUE THREAD

**Issue by kirikak2** [yasslab/railsguides.jp#689]
初めての報告となるので、不備等ありましたらすみません。

Railsルーティングの「単数形リソース」の項目で `to: :show` というオプションが使われているルーティング定義があるのですが、このオプションはRails5.2において既に使えない形式となっているようです。

https://github.com/yasslab/railsguides.jp/blame/master/guides/source/ja/routing.md#L145

原文を確認してみたのですが、こちらは`action: :show` に修正されているようです。

http://guides.rubyonrails.org/routing.html#singular-resources

**Comment by riseshia** [comment]
確認ありがとうございます！！ #690 で対応 PR を出しました。
