### ISSUE TITLE
CIがパスしてないときはマージできないようにしたい

### ISSUE THREAD

**Issue by nanophate** [yasslab/railsguides.jp#692]
## やりたいこと

下の画像のようにCIがFailしているのに、マージできるようになっている、https://github.com/yasslab/railsguides.jp/pull/615#pullrequestreview-142312537 があるので、誤ってマージをクリックできないようにしたい。
 
![CIがFailしているのに、マージできる](https://user-images.githubusercontent.com/6015450/43516629-17c0a29e-95c1-11e8-8e9b-cdc45f29c226.png)

**Comment by shishi** [comment]
branch statusってやつですね

**Comment by yasulab** [comment]
CI は失敗しているけど致命的なエラーがあるので迅速に直したい場合 (例えばエラーが直せるまでユーザーが一切アクセスできなくなる場合とか) はどうするんだろう？ 🤔 テストが全部パスするまでユーザーには我慢してもらう感じかな？

**Comment by yasulab** [comment]
🤔.oO(まぁ内部のコードに対する PR はあまり来ないので、そういったケースに陥るケース自体が結構稀かも?)

**Comment by nanophate** [comment]
> 致命的なエラーがあるので迅速に直したい場合 (例えばエラーが直せるまでユーザーが一切アクセスできなくなる場合とか)

masterにマージされても、テストが取らない場合はherokuにdeployされないと思っていました。

**Comment by yasulab** [comment]
たしかに...!! 😆✨

**Comment by nanophate** [comment]
☝️ のような緊急状況の場合は[CI SKIP] でマージする状態を意図的に作って、テストを通さないでherokuにdeployする方法も取れた方が良さそうですね 🤔
