### ISSUE TITLE
スタートガイド誤植訂正

### ISSUE THREAD

**Issue by nosukeru** [yasslab/railsguides.jp#697]
日本語のスタートガイドを読ませて頂いていて気になる箇所がいくつかあったので指摘させていただきます。

5.3節
・原文
We just added the create action but didn't specify anything about how the response should be. In this case, the create action should save our new article to the database.

・訳文
ここではcreateアクションを追加しただけで、レスポンスの振る舞いについて何も指定していませんので、新しい記事はcreateアクションによってデータベースに保存されているはずです。

・修正案
今の段階ではcreateアクションを追加しただけで、レスポンスの振る舞いについて何も指定していません。ここでは、createアクション内に新しい記事をデータベースに保存する処理を書く必要があります。

5.10節
・原文
There isn't much to this file - but note that the Article class inherits from ApplicationRecord. ApplicationRecord inherits from ActiveRecord::Base which supplies a great deal of functionality to your Rails models for free,

・訳文
ファイルにはこれしか書かれていませんが、このArticleクラスがActiveRecord::Baseクラスを継承していることにご注目ください。そのActiveRecord::BaseはさらにActiveRecord::Baseを継承しており、

・修正案
ファイルにはこれしか書かれていませんが、このArticleクラスがApplicationRecordクラスを継承していることにご注目ください。そのApplicationRecordはさらにActiveRecord::Baseを継承しており、

よろしくお願いいたします。

**Comment by yasulab** [comment]
こちら現在は修正済みとなっているので一旦 Close しますね！フィードバックありがとうございました！(＞人＜ )💖
