### ISSUE TITLE
本家の rails/rails に Guides の国際化 PR を送る (任意)

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#7]
もし本家 docrails へのPRに興味ある方は是非!
なお，日本語版では下記の Issue/PR で既に修正されています。

- Issue: #3 [railsguides/bundle exec rake guides:generateがうまくいかない問題について原因と解決策案 #railsguide](https://github.com/yasslab/railsguides.jp/issues/3)
- Pull Request: #4 [ID を日本語にした](https://github.com/yasslab/railsguides.jp/pull/4)
- [rails/rails - GitHub](https://github.com/rails/rails)

**Comment by yui-knk** [comment]
こちらなんですが

```
commit 2735b9cf97947cd0a59b0b72264d865598380879
Date:   Sun Aug 24 11:58:01 2014 +0800

    Fix guide anchor generation logic.

    This could use in any translation because it's not limited to `[^a-z0-9]`.

    Verify after this change, all guides still have same anchors.

    [Robin Dupret & Juanito Fatas]
```

で対応されているような気がします

**Comment by yasulab** [comment]
おぉ、情報ありがとうございます!
