### ISSUE TITLE
GTTの翻訳で文頭に空白をいれてもzipの内容に反映されない

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#71]
http://railsguides.jp/configuring.htmlの"3.10 Action Mailerを設定する"で

```
ハッシュを1つ指定してオプションを追加することもできます。
```

というところのインデントがくずれており(空白４つが必要)GTTで編集したのですが、ダウンロードしたzipを展開しても反映されません。対処法などありませんか？

**Comment by yasulab** [comment]
@yui-knk 

GTTが勝手に Squash しちゃうみたいなんですよね。というわけで、空白スペースの数に応じた置換コードを実はいくつか仕込んでおります :shipit: 

詳細は Wiki に書いてあるのでコチラをどうぞ! :+1: 

https://github.com/yasslab/railsguides.jp/wiki/%E7%BF%BB%E8%A8%B3%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8BTIPS#gtt%E4%B8%8A%E3%81%A7%E7%A9%BA%E7%99%BD%E3%82%B9%E3%83%9A%E3%83%BC%E3%82%B9%E3%81%8C%E5%9C%A7%E7%B8%AE%E3%81%95%E3%82%8C%E3%81%A6%E3%81%97%E3%81%BE%E3%81%86%E5%95%8F%E9%A1%8C

**Comment by yui-knk** [comment]
@yasulab  承知しました。ありがとうございます！
https://github.com/yasslab/railsguides.jp/commit/7f66996bb6ef2e4123c7ab1694da9b111cbb6461
で対応しました！
