### ISSUE TITLE
誤字？　Active Recordクエリインターフェイス - 17 SQLで検索する

### ISSUE THREAD

**Issue by tkiha** [yasslab/railsguides.jp#72]
以下の箇所、誤字ではないでしょうか。

17 SQLで検索する
find_by_sqlメソッドを強いようできます。→ find_by_sqlメソッドを使用できます。

**Comment by yui-knk** [comment]
ご指摘、ありがとうございます。

```
you can use `find_by_sql`
```

ですので"使用できます"が正しいですね。
修正いたします。
