### ISSUE TITLE
セキュリテイガイドの一部の文章が前後している

### ISSUE THREAD

**Issue by tsurugeek** [yasslab/railsguides.jp#733]
「Note that negative CAPTCHAs are only effective against dumb bots and won't suffice to protect critical applications from targeted bots. Still, the negative and positive CAPTCHAs can be combined to increase the performance, e.g., if the "honeypot" field is not empty (bot detected), you won't need to verify the positive CAPTCHA, which would require an HTTPS request to Google ReCaptcha before computing the response.」

の訳である

「ネガティブCAPTCHAが効果を発揮するのはWebをクロールする自動ボットからの保護のみであり、重要なサイトに狙いを定めるボットの保護には不向きです。しかしネガティブCAPTCHAとポジティブCAPTCHAをうまく組み合わせればパフォーマンスを改善できることがあります。たとえば"honeypot"フィールドが空でない場合（=ボットが検出された）はポジティブCAPTCHAの検証は不要になり、レスポンス処理の前にGoogle ReCapchaにHTTPSリクエストを送信せずに済みます。」

の位置が本来の位置と異なっています。もっと前の方に移動すべきかと思います。

**Comment by hachi8833** [comment]
フィードバックありがとうございます！確認・修正しますね
