### ISSUE TITLE
Heroku Review Apps を railsguides.jp でも使いたい

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#766]
~~coderdojo.jp や~~ railstutorial.jp では導入済み ✅ Review Apps はメッチャ便利で、 例えば[こういったテストで見抜きにくいエラー](https://github.com/yasslab/railsguides.jp/pull/765#issuecomment-450784473)に事前に気づけるし、デザインのレビューでもスクショなどをコメント欄に貼る必要がなくなるので、Railsガイドでも導入したい 🚀🚀🚀 ✨ 

Review Apps | Heroku Dev Center
https://devcenter.heroku.com/articles/github-integration-review-apps

**Comment by yasulab** [comment]
🤔.oO(ここは経験者のアナグラさんにお任せした方が良さそうかな...?)

**Comment by AnaTofuZ** [comment]
以前同様のタスクを着手したので，当時のお気持ちを調査しながら設定していきます!

**Comment by yasulab** [comment]
なるほど yasslab.jp だと @yasulab アカウントになってるのか 👀 

![image](https://user-images.githubusercontent.com/155807/50585453-5f784680-0eb8-11e9-96e7-019677d97454.png)

あと勢いで「coderdojo.jp や ...」って書いたけど、さっき試しに PR を出してみたら coderdojo.jp は Heroku Review Apps 未対応だった 😅 

cf. [Bundle update i18n and pry-rails gems #368 - coderdojo-japan/coderdojo.jp](https://github.com/coderdojo-japan/coderdojo.jp/pull/368)
![image](https://user-images.githubusercontent.com/155807/50585761-e548c180-0eb9-11e9-9faf-2543e2266bd9.png)
