### ISSUE TITLE
内部リンクを自動的に置換できるようにしたい

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#79]
内部リンクはセクション名に依存しているため、セクション名を翻訳する必要があるRailsガイドでは、ほぼ必ず内部リンクが壊れてしまいます。毎回手作業で修正しているのですが、面倒なのでコレをなんとか自動化できないものかな... :sweat: 

> 内部リンクの修正事例: https://github.com/yasslab/railsguides.jp/pull/78/files

改善案:
1. 原文のセクション名と訳文のセクション名のテーブルを用意して、
2. HTMLを生成する際に、そのテーブルを参照して内部リンクを置換する
3. たまに反応しないリンク(日本語の文字コードが原因?)があるので、それに対するescapeも適宜処理する

**Comment by takahashim** [comment]
これですが、どちらかというとPHP Markdown ExtraやPandocが持っているヘッダ属性を導入するのがよいかと思いました（Redcarpetは標準では対応していないのがつらいところですが…）
https://michelf.ca/projects/php-markdown/extra/#spe-attr
http://johnmacfarlane.net/pandoc/README.html#header-identifiers-in-html-latex-and-context

**Comment by yasulab** [comment]
(めっちゃ反応遅れて大変恐縮ですが) 情報ありがとうございます! 

Pandoc、色々と優秀そうですね。電子書籍化コンバータの件でももしかしたら使えるかもしれないので、Pandocを調査してみます! :mag:
