### ISSUE TITLE
i18n.htmlの脚注の2, 3が表示されない

### ISSUE THREAD

**Issue by sho-h** [yasslab/railsguides.jp#80]
何が問題なのかがわからないのですが、脚注の2, 3が表示されていないようです。
(見比べてみるにtypo等もないようなのですが...)

**Comment by yasulab** [comment]
確かに表示されてないですね :sweat: 

- http://railsguides.jp/i18n.html#footnote-1
- http://guides.rubyonrails.org/i18n.html#footnote-1

おそらくですが、Generator の中で日本語 (マルチバイト文字) に対応していない処理をしてるのが原因っぽい気がします (あとで調べよう...)

**Comment by yui-knk** [comment]
https://github.com/yui-knk/redcarpet/tree/feature/sample_md

で実験しましたが、今のRails内でのredcarpetの使い方で日本語ファイルを食べさせると、うまくいかないようですね。

```
    renderer = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      autolink: true,
      strikethrough: true,
      superscript: true,
      tables: true,
      footnotes: true
    )
```

と`footnotes`をつければrender自体はできるので、オプションを増やして、`convert_footnotes`メソッド等を調整したほうがいいのかもしれません。

ベストは、Rails本家でもoptionを渡すように修正することですが・・・

**Comment by yui-knk** [comment]
[このあたり](https://github.com/yasslab/railsguides.jp/blob/japanese/guides/rails_guides/markdown/renderer.rb#L32)にpryを仕込んで確認したところ

```
"Active Supportにデフォルトで装備されている「シンプルな」バックエンドを使用している場合、純粋なRubyファイル形式およびYAMLフォーマット<a href=\"%E3%81%93%E3%81%AE%E4%BB%96%E3%81%AE%E3%83%90%E3%83%83%E3%82%AF%E3%82%A8%E3%83%B3%E3%83%89%E3%81%A7%E3%81%AF%E3%80%81%E7%95%B0%E3%81%AA%E3%82%8B%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%83%E3%83%88%E3%81%8C%E5%88%A9%E7%94%A8%E3%81%A7%E3%81%8D%E3%81%9F%E3%82%8A%E3%80%81%E5%BF%85%E9%A0%88%E3%81%A8%E3%81%95%E3%82%8C%E3%82%8B%E5%8F%AF%E8%83%BD%E6%80%A7%E3%81%8C%E3%81%82%E3%82%8A%E3%81%BE%E3%81%99%E3%80%82%E3%81%9F%E3%81%A8%E3%81%88%E3%81%B0%E3%80%81GetText%E3%83%90%E3%83%83%E3%82%AF%E3%82%A8%E3%83%B3%E3%83%89%E3%81%AFGetText%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E8%AA%AD%E3%81%BF%E8%BE%BC%E3%82%81%E3%82%8B%E3%81%A7%E3%81%97%E3%82%87%E3%81%86%E3%80%82\"><sup>2</sup></a>が使用できます。"
```

このようなtextが生成されています。
`[]`をlinkと判断して、脚注の内容をもってきているようです。
ためしにredcarpetを3.2.2にあげても、同じでした

**Comment by yasulab** [comment]
こちら、 #93 の PR で原因と応急処置は済みました :wrench: (Thx! @yui-knk )

ですが、運用時に注意しておこないと同様の現象が起こる可能性があるので、理想的にはスクリプトなどによる対策が必要かな、といった状況です。なので、機械的な対策が施されるまでは、こちらの issue は close せずにしておこうかなと考えています :bow:

**Comment by sho-h** [comment]
対応ありがとうございます！
