### ISSUE TITLE
Rails考古学: 古いリリースノートを翻訳する

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#830]
@hachi8833 お願いします...!! (＞人＜ )✨

## 進捗状況 📝 ✅ 

- [x] [Ruby on Rails 3.2 リリースノート](https://railsguides.jp/3_2_release_notes.html)
- [x] [Ruby on Rails 3.1 リリースノート](https://railsguides.jp/3_1_release_notes.html)
- [x] [Ruby on Rails 3.0 リリースノート](https://railsguides.jp/3_0_release_notes.html)
- [x] [Ruby on Rails 2.3 リリースノート](https://railsguides.jp/2_3_release_notes.html)
- [x] [Ruby on Rails 2.2 リリースノート](https://railsguides.jp/2_2_release_notes.html)

**Comment by hachi8833** [comment]
近々に対応します🙇‍♂️🙇‍♂️

**Comment by yasulab** [comment]
こちら無事公開されたので Close しますね! ご対応ありがとうございました...!! (＞人＜ )💖 https://twitter.com/yasulab/status/1506885993584263168
