### ISSUE TITLE
action_controller_overview (8.2 その他のフィルタ使用法)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#84]
```
1番目は、*actionメソッドに対して直接ブロックを与えることです。このブロックはコントローラを引数として受け取り、その上の`requirelogin`フィルタを書き換えて、ブロックを使用するようにします。●
```

http://railsguides.jp/action_controller_overview.html#%E3%81%9D%E3%81%AE%E4%BB%96%E3%81%AE%E3%83%95%E3%82%A3%E3%83%AB%E3%82%BF%E4%BD%BF%E7%94%A8%E6%B3%95

ですが、`_`のエスケープが抜けていました。

本家のdocは以下で修正しました。
https://github.com/rails/rails/commit/6b4c5aeb35471d43122a829c88662b6886d9171a

備忘録としてissueにしておきます。

**Comment by hachi8833** [comment]
ありがとうございます! GTT にも反映しました

**Comment by yui-knk** [comment]
確認しました。ありがとうございました！
