### ISSUE TITLE
ORMの訳について(表記ゆれ)

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railsguides.jp#86]
表記ゆれがあります。

`ORM(オブジェクトリレーショナルマッピング)`などに統一してはいかがでしょうか？

+ active_model_basics.md

`Active Model also helps building custom ORMs for use outside of the Rails framework`
=>
`Active Modelを使用することで、カスタムのORM (オブジェクト/リレーションモデル) を作成してRailsフレームワークの外で使用することもできます。`

+ active_record_basics.md

`It is an implementation of the Active Record pattern which itself is a description of an Object Relational Mapping system.`
=>
`Active Recordは、オブジェクトリレーションマッピング(ORM: Object Relation Mapping)システムに記述されている「Active Recordパターン」を実装したものであり、同じ名前が付けられています。`

+ active_record_basics.md

`Object-Relational Mapping, commonly referred to as its abbreviation ORM, is a technique that connects the rich objects of an application to tables in a relational database management system.`
=>
`オブジェクトリレーションマッピング(O/RマッピングやORMと略されることもあります)とは、アプリケーションが持つリッチなオブジェクトをリレーショナルデータベース(RDBMS)のテーブルに接続するものです。`

+ form_helpers.md

`You may wish to do this if the autogenerated input is placed in a location where an input tag is not valid HTML or when using an ORM where children do not have an `id`.`
=>
`自動生成をオフにすることがあるとすれば、HTMLが有効でなくなってしまうような場所にinputタグが生成されないようにする場合や、子が`id`を持たないO/RM (オブジェクト-リレーションマッピング) を使用したい場合があります。`

**Comment by hachi8833** [comment]
ご指摘ありがとうございます。週末に確認しますね。

**Comment by hachi8833** [comment]
訳語を統一しました。configuring.mdも修正しました。

**Comment by yui-knk** [comment]
確認しました！　ありがとうございます
