### ISSUE TITLE
各ガイドに解説記事や参考記事を紹介するセクションを設けたい

### ISSUE THREAD

**Issue by yasulab** [yasslab/railsguides.jp#88]
次のような記事を読んでいると、 各ガイド + 合わせて読みたい記事などが読者に役に立っていそうなので、そういった各ガイドに関する解説記事や参考記事を紹介するセクションを設けてもよいのかなぁと考えています。

Railsで、model 直下に rbファイルと、同名のディレクトリがある際に挙動がおかしい
http://tkm9.hateblo.jp/entry/2015/02/17/000056

例えば、
- [定数の自動読み込みと再読み込み](http://railsguides.jp/constant_autoloading_and_reloading.html) の末尾で [Railsガイドを読む(定数の自動読み込みと再読み込み)](http://qiita.com/yui-knk/items/8f7e693b89423d983097)を参考リンクとして紹介する
- [Railsをはじめよう](http://railsguides.jp/getting_started.html)の末尾で[Ruby on Rails ガイドのすすめ](http://qiita.com/yui-knk/items/4b4aaf4b8dea049efe6e)を紹介する

といった感じのイメージです。

具体的には、ガイドの末尾で紹介するリンクを yaml で書いて、ここら辺で読み込むとか (?):
https://github.com/yasslab/railsguides.jp/blob/japanese/guides/source/layout.html.erb#L111-L116

**Comment by yui-knk** [comment]
#89  によりcloseします
