### ISSUE TITLE
ルーティングページの脱字訂正

### ISSUE THREAD

**Issue by kichinaga** [yasslab/railsguides.jp#894]
ルーティングページの3.4節にて、部分的に文章が欠落しているところがあったため指摘させていただきます。

[Rails のルーティング 3.4 クエリ文字列](https://railsguides.jp/routing.html#%E3%82%AF%E3%82%A8%E3%83%AA%E6%96%87%E5%AD%97%E5%88%97)

誤:
```
photos/:id', to: 'photos#show'
```

訂:
```
get 'photos/:id', to: 'photos#show'
```

よろしくお願いいたします。

**Comment by y-kawa** [comment]
長らく放置されていたため取り組みました。
https://github.com/yasslab/railsguides.jp/pull/982 こちらのPRで脱字を修正しています。
