### ISSUE TITLE
「3.2.4 asとobjectオプション」の誤訳

### ISSUE THREAD

**Issue by mtakahashi-ivi** [yasslab/railsguides.jp#975]
「3.2.4 asとobjectオプション」で以下の文章があります。

> 上のコードでは、ローカル変数である`_product`の中に`@product`が置かれます。これは以下のコードと同等の結果になります。

原文は以下です
> within `_product` partial we'll get `@product` in the local variable `product`, as if we had written:

これは以下のような訳の方が正しいのではないでしょうか？

上のコードでは、`_product`パーシャルはローカル変数`product`から`@product`を取得できます。これは以下のコードと同等の結果になります。

**Comment by hachi8833** [comment]
こちら https://github.com/yasslab/railsguides.jp/commit/c84fe6841064c466eafd568611878239fbba5e03#diff-88ac90947189149f042c8609a927026f4319410a00958a9f09d28c3f038bb4ec で修正いただきありがとうございます！
本件closeします。
