### ISSUE TITLE
複数DBの使用についての翻訳が二つのファイルに分裂してしまっている

### ISSUE THREAD

**Issue by takayamaki** [yasslab/railsguides.jp#986]
https://github.com/yasslab/railsguides.jp/pull/983 のPR本文でも言及していますが、複数DBの使用に関する翻訳が https://github.com/yasslab/railsguides.jp/pull/848 と https://github.com/yasslab/railsguides.jp/pull/849 によって [active_record_multiple_database.md](https://github.com/yasslab/railsguides.jp/blob/master/guides/source/ja/active_record_multiple_database.md) と [active_record_multiple_databases.md](https://github.com/yasslab/railsguides.jp/blob/master/guides/source/ja/active_record_multiple_databases.md) に分裂してしまっています。

単に削除するだけならば簡単ですが、それぞれのファイルに異なる編集が加えられているため、どちらの翻訳を採用すれば良いのか判別できません。

**Comment by hachi8833** [comment]
@takayamaki ご指摘ありがとうございます！🙇
これはファイル名末尾に"s"が付いている [active_record_multiple_databases.md](https://github.com/yasslab/railsguides.jp/blob/master/guides/source/ja/active_record_multiple_databases.md)の方が訳が新しい正規のものです。

[active_record_multiple_database.md](https://github.com/yasslab/railsguides.jp/blob/master/guides/source/ja/active_record_multiple_database.md)の削除をお願いします。

**Comment by yasulab** [comment]
> [active_record_multiple_database.md](https://github.com/yasslab/railsguides.jp/blob/master/guides/source/ja/active_record_multiple_database.md)の削除をお願いします。

こちら承知しました！それではこちらの削除は僕の方で後ほど対応しておきますね 🛠💨✨
